/* Sound for the Living Cabinet: a chip-groove soundtrack and the cabinet's effects.
 * Music (crucible_music_data.h, format keel_music.h, scores generated by the music toolchain) is the trailer bed's style:
 * a 16th-note grid of register-level hits, kicks on pulse 1 (a falling sweep) between stabs, a 25 % arpeggio lead on
 * pulse 2, the cabinet's pad wave as a gated bass, and noise snares, claps, hats and risers. Songs follow the screen,
 * the clock and the story (pick_song), change on a short gap, keep the screen's time, and swap sections for their
 * alternates from their own seed so long play does not repeat exactly.
 * Effects use pulse 1 and noise; pulse 2 and wave keep the melody and bass audible. Actions also stir the music
 * seed and briefly vary the lead octave and duty, without resetting the score or lowering its volume.
 * Every object has a voice: a four-note motif from its id and a timbre from its category, so focusing,
 * picking, merging and revealing it sound like that object, and every discovery fanfare is its own. */
#pragma bank 255
#include <gb/gb.h>
#include "crucible_state.h"
#include "crucible_time.h"
#include "crucible_storyrun.h"
#include "crucible_link.h"
#include "keel_music.h"
#include "crucible_music_data.h"
#include "crucible_volume.h"
/* note: frames, envelope (NRx2), frequency low, duty<<6 | frequency high (noise: low byte is NR43) */
/* Authored effects store key-relative semitones; runtime lists store GB frequencies. */
#define N(f, e, n, d) f, e, (uint8_t)(n), (uint8_t)(d << 6)
#define X(f, e, p) f, e, p, 0
#define END 0
enum { C4 = 12, Eb4 = 15, G4 = 19, C5 = 24, D5 = 26, Eb5 = 27, G5 = 31, A5 = 33, C6 = 36 };
/* C3..B6, GB pulse frequency registers; the wave channel sounds an octave lower for the same value. */
#define notes (km_period + 12)
static const uint8_t undo1[] = {N(3, 0x71, A5, 2), N(6, 0x62, Eb5, 2), END};
static const uint8_t mix1[] = {N(14, 0x83, C4, 2), END}, mix4[] = {X(12, 0x42, 0x45), END};
static const uint8_t bubble4[] = {X(2, 0x41, 0x3c), X(3, 0x31, 0x2b), END};
static const uint8_t swap1[] = {N(3, 0x81, C5, 1), END};
static const uint8_t flash1[] = {N(8, 0xa2, C6, 1), END}, flash4[] = {X(12, 0x83, 0x61), END};
static const uint8_t nothing1[] = {N(6, 0x72, Eb4, 1), N(14, 0x63, C4, 1), END}, nothing4[] = {X(6, 0x51, 0x6d), END};
static const uint8_t open1[] = {N(3, 0x61, C5, 2), N(5, 0x62, G5, 2), END},
                     close1[] = {N(3, 0x61, G5, 2), N(5, 0x62, C5, 2), END};
static const uint8_t deny1[] = {N(4, 0x91, C4, 3), N(8, 0x92, C4, 3), END};
static const uint8_t move1[] = {N(2, 0x31, D5, 2), END};
/* the partner made something: two rising notes; the partner missed: a short falling noise (fight spec 9.5) */
static const uint8_t pmade1[] = {N(3, 0x71, G5, 2), N(6, 0x72, C6, 2), END},
                     pmiss4[] = {X(3, 0x41, 0x5d), X(5, 0x31, 0x6e), END};
/* already on the shelf: a quick bright double tap, falling, with a soft tick (distinct from discovery) */
static const uint8_t known1[] = {N(3, 0x81, G5, 2), N(3, 0x51, Eb5, 2), N(6, 0x62, C5, 2), END},
                     known4[] = {X(2, 0x21, 0x2b), END};
typedef struct {
  const uint8_t *ch1, *ch2, *ch4;
} sfx_t;
static const sfx_t table[] = {{0, 0, 0},       {move1, 0, 0},   {0, 0, 0},           {undo1, 0, 0},
                              {mix1, 0, mix4}, {0, 0, bubble4}, {swap1, 0, 0},       {flash1, 0, flash4},
                              {0, 0, 0},       {pmade1, 0, 0},  {known1, 0, known4}, {nothing1, 0, nothing4},
                              {open1, 0, 0},   {close1, 0, 0},  {deny1, 0, 0},       {0, 0, pmiss4}};
static const uint8_t *at[3];
static uint8_t left[3], pitch;
/* Runtime note lists for voices and fanfares (up to seven notes per channel). */
static uint8_t vbuf[3][32];
static void silence(uint8_t ch) {
  if (ch == 0)
    NR12_REG = 0;
  else if (ch == 1)
    NR22_REG = 0;
  else
    NR42_REG = 0;
}
static uint8_t s_vol;
/* an effect's envelope at the SFX volume (8: as written) */
static uint8_t sfx_env(uint8_t e) {
  uint8_t v;
  if (s_vol >= 8u) return e;
  v = (uint8_t)(((e >> 4) * s_vol + 4u) >> 3);
  if (!v && (e >> 4)) v = 1u;
  return (uint8_t)((v << 4) | (e & 15u));
}
static void start(uint8_t ch) {
  const uint8_t *n = at[ch];
  uint16_t hz;
  if (!n || !n[0]) {
    at[ch] = 0;
    silence(ch);
    return;
  }
  left[ch] = n[0];
  hz = ((uint16_t)(n[3] & 7u) << 8) | n[2];
  if (ch == 0) {
    if (pitch) {
      hz += pitch;
      if (hz > 2040u) hz = 2040u;
    }
    NR10_REG = 0;
    NR11_REG = n[3] & 0xc0u;
    NR12_REG = sfx_env(n[1]);
    NR13_REG = (uint8_t)hz;
    NR14_REG = 0x80u | (uint8_t)(hz >> 8);
  } else if (ch == 1) {
    NR21_REG = n[3] & 0xc0u;
    NR22_REG = sfx_env(n[1]);
    NR23_REG = (uint8_t)hz;
    NR24_REG = 0x80u | (uint8_t)(hz >> 8);
  } else {
    NR41_REG = 0;
    NR42_REG = sfx_env(n[1]);
    NR43_REG = n[2];
    NR44_REG = 0x80u;
  }
}
/* ---- shared state ---- */
static const uint8_t workshop_scale[5] = {0, 2, 3, 7, 9};
static uint8_t mood, root, music_level, sfx_off, wave_left;
static uint16_t seed;
static uint8_t reaction_left, reaction_octave, reaction_duty;
/* wave output level: full music at 50%, soft music at 25% (NR32 bits 6-5) */
#define BED(level) (music_level ? 0x60u : (level))
static uint8_t rnd(void) {
  seed ^= seed << 7;
  seed ^= seed >> 9;
  seed ^= seed << 8;
  return (uint8_t)seed;
}
/* ---- the soundtrack ---- */
#define M_OFF 0u
#define M_PLAY 1u
#define M_OUT 2u /* fading the song out (it keeps playing) before the next one comes in on a beat */
#define M_WAIT 3u /* a short wait before the first song (the screen's scene arrives in this frame) */
#define G_FULL 16u /* fade gain: 0..16 */
uint8_t music_force; /* a test harness may pick a SONG_* here (255: the game picks) */
static uint16_t m_seed, m_heard, m_last;
static const uint8_t *m_s, *m_sec, *m_p[4];
static uint8_t m_state, m_scene, m_song, m_want, m_t, m_wave, m_pan, m_span, m_frames, m_night, m_wraps, m_clock, m_row,
    m_bar, m_order;
/* volume: m_vol the MUSIC setting (0..8), m_gain the fade ramp toward m_goal (a step every m_rate frames), m_k the
 * scale every hit gets (0..128 = vol*gain), m_bassl the held bass's
 * level (rescaled as the ramp moves) */
static uint8_t m_vol, m_gain, m_goal, m_rate, m_rt, m_k, m_bassl, m_fast;
static void load_wave(uint8_t w) {
  uint8_t i;
  const uint8_t *p = km_wave + (uint8_t)(w << 4);
  NR30_REG = 0;
  for (i = 0; i < 16u; i++) AUD3WAVE[i] = p[i];
  NR30_REG = 0x80u;
  m_wave = w;
}
/* effects keep the bed at its chosen volume: the quantized wave gain never ducks to zero */
static void set_k(void) {
  uint8_t k = (uint8_t)(m_vol * m_gain);
  m_k = k;
}
/* an envelope at the music's volume (a scaled start volume keeps its pace) */
static uint8_t scale(uint8_t e) {
  uint8_t v = (uint8_t)(((uint16_t)(e >> 4) * m_k + 64u) >> 7);
  if (!v && m_k && (e >> 4)) v = 1u;
  return (uint8_t)((v << 4) | (e & 15u));
}
/* the wave channel has four levels: pick the nearest for its instrument's level at the music's volume */
static uint8_t wave_level(uint8_t l) {
  uint8_t s = m_k;
  if (l >= 0x40u) s >>= 1;
  if (l >= 0x60u) s >>= 1;
  return s >= 96u ? 0x20u : s >= 48u ? 0x40u : s >= 24u ? 0x60u : 0u;
}
/* one event: e[0] the note (noise: NR43), e[1] the instrument. A channel an effect holds is left alone. */
static void play(uint8_t c, const uint8_t *e) {
  const uint8_t *in = km_inst + (uint8_t)(e[1] << 2);
  uint8_t n = e[0];
  uint16_t x;
  if (c == 3u) {
    if (at[2]) return;
    NR41_REG = in[1];
    NR42_REG = scale(in[2]);
    NR43_REG = n;
    NR44_REG = 0x80u | in[3];
    return;
  }
  if (c == 2u) {
    if (wave_left) return;
    if (n == KM_OFF) {
      m_bassl = 0;
      NR32_REG = 0;
      return;
    }
    x = km_period[n];
    m_bassl = in[2];
    NR31_REG = in[1];
    NR32_REG = wave_level(in[2]);
    NR33_REG = (uint8_t)x;
    NR34_REG = (uint8_t)(0x80u | in[3] | (uint8_t)(x >> 8));
    return;
  }
  if (at[c]) return;
  if (n == KM_OFF) {
    if (c)
      NR22_REG = 0;
    else
      NR12_REG = 0;
    return;
  }
  if (c == 1u && reaction_left && n + reaction_octave < 72u) n += reaction_octave;
  x = km_period[n];
  if (c == 0u) {
    NR10_REG = in[0];
    NR11_REG = in[1];
    NR12_REG = scale(in[2]);
    NR13_REG = (uint8_t)x;
    NR14_REG = (uint8_t)(0x80u | in[3] | (uint8_t)(x >> 8));
  } else {
    NR21_REG = reaction_left ? (uint8_t)((in[1] & 63u) | (reaction_duty << 6)) : in[1];
    NR22_REG = scale(in[2]);
    NR23_REG = (uint8_t)x;
    NR24_REG = (uint8_t)(0x80u | in[3] | (uint8_t)(x >> 8));
  }
}
/* fresh: ask the clock (costly: a screen change, or every fourth loop of a song) */
static uint8_t pick_song(uint8_t fresh) {
  crucible_time_ctx t;
  crucible_story *s;
  if (music_force < KM_SONGS) return music_force;
  if (m_scene == 8u) return SONG_BOSS_DROP;
  if (m_scene == 9u || link_on) return SONG_LINK_BUSY;
  if (m_scene == 7u) return SONG_TALK_STRIP;
  if (m_scene == 3u || m_scene == 4u || m_scene == 6u) return SONG_BOOK_LIGHT;
  if (story_on && (s = talk_saga()) != 0) {
    if (s->chapter >= CRU_STORY_CHAPTERS) return SONG_ENDING_LIFT;
    if (s->lucid < 64u) return SONG_LOST_GROOVE;
  }
  if (fresh) {
    crucible_time_context(&t);
    m_night = (uint8_t)((t.flags & CT_F_KNOWN) && t.part == CT_NIGHT);
  }
  if (m_night) return SONG_NIGHT_GROOVE;
  return m_scene == 5u ? SONG_TITLE_PUNCH : SONG_BENCH_GROOVE;
}
static const uint8_t *section_of(uint8_t k) {
  const uint8_t *s = m_s;
  return s + km_u16(s + KM_S_ORDER + s[KM_S_COUNT] + 1u + (uint8_t)(k << 1));
}
static void bar_start(void) {
  const uint8_t *ids = m_sec + 2u + (uint8_t)(m_bar << 2);
  uint8_t c;
  for (c = 0; c < 4u; c++) m_p[c] = ids[c] == KM_NONE ? 0 : km_pat + km_pat_at[ids[c]];
}
/* a section may be replaced by its alternate (a fill, a variation) on about one pass in three */
static void section_start(void) {
  uint8_t alt;
  m_sec = section_of(m_s[KM_S_ORDER + m_order]);
  alt = m_sec[1];
  if (alt != KM_NONE && km_rnd(&m_seed) < 86u) m_sec = section_of(alt);
  m_bar = m_row = 0;
  bar_start();
}
static void ramp(uint8_t goal, uint8_t rate) {
  m_goal = goal;
  m_rate = rate;
  m_rt = rate;
}
/* fight music cuts in on its downbeat at full level; the others fade in over half a second */
static void song_start(uint8_t id) {
  const uint8_t *s = km_song + km_song_at[id];
  m_song = id;
  m_s = s;
  m_state = M_PLAY;
  m_clock = 0;
  m_frames = s[KM_S_FRAMES];
  m_span = s[KM_S_PAN];
  m_order = (m_heard & (1u << id)) ? s[KM_S_LOOP] : 0u;
  m_heard |= (uint16_t)(1u << id);
  if (id == SONG_BOSS_DROP) {
    m_gain = G_FULL;
    ramp(G_FULL, 1);
  } else {
    m_gain = 4u;
    ramp(G_FULL, 2);
  }
  set_k();
  if (s[KM_S_WAVE] != m_wave && !wave_left) {
    NR32_REG = 0;
    load_wave(s[KM_S_WAVE]);
  }
  section_start();
}
static void music_stop(void) {
  m_state = M_OFF;
  m_bassl = 0;
  if (!wave_left) {
    NR32_REG = 0;
    if (m_wave != KM_WAVE_PAD) load_wave(KM_WAVE_PAD);
  }
}
static void music_go(void) {
  if (!m_vol) {
    music_stop();
    return;
  }
  if (m_state == M_OFF) {
    m_state = M_WAIT;
    m_t = 4;
  }
}
/* A change of song fades the old one out while it keeps playing (about 0.6 s; 0.2 s into a fight), then the next
 * one starts on a beat. */
static void fade_to(uint8_t song) {
  m_want = song;
  if (m_state != M_PLAY && m_state != M_OUT) return;
  if (song == m_song && m_state == M_PLAY) return;
  m_fast = (uint8_t)(song == SONG_BOSS_DROP);
  m_state = M_OUT;
  ramp(0, m_fast ? 1u : 3u);
}
static void row_tick(void) {
  const uint8_t *p;
  uint8_t c, k;
  if (music_force < KM_SONGS && music_force != m_want && music_force != m_song) fade_to(music_force);
  /* nearly faded out: the next song comes in on the next beat, where the old one is still a whisper (no silent gap);
  * if the fade finished between beats, on the next row */
  if (m_state == M_OUT && (!m_gain || (m_gain <= 4u && (m_fast || !(m_row & 3u))))) song_start(m_want);
  for (c = 0; c < 4u; c++) {
    p = m_p[c];
    if (p && p[0] == m_row) {
      play(c, p + 1);
      m_p[c] = p + 3;
    }
  }
  if (++m_row < 16u) return;
  m_row = 0;
  if (++m_bar < m_sec[0]) {
    bar_start();
    return;
  }
  if (++m_order >= m_s[KM_S_COUNT]) {
    m_order = m_s[KM_S_LOOP];
    if (m_state == M_PLAY) {
      k = pick_song((uint8_t)(!(++m_wraps & 3u)));
      if (k != m_song) fade_to(k);
    }
  }
  section_start();
}
static void music_tick(void) {
  uint8_t p, e = (uint8_t)(sys_time - m_last), k;
  m_last = sys_time;
  if (reaction_left) reaction_left = reaction_left > e ? (uint8_t)(reaction_left - e) : 0u;
  if (e > 8u) e = 8u;
  if (wave_left && !--wave_left) {
    NR32_REG = 0;
    if (m_state == M_OFF && m_wave != KM_WAVE_PAD) load_wave(KM_WAVE_PAD);
  }
  p = m_state == M_OFF ? 0xffu : m_span;
  if (at[0]) p |= 0x11u;
  if (at[1]) p |= 0x22u;
  if (at[2]) p |= 0x88u;
  if (wave_left) p |= 0x44u;
  if (p != m_pan) {
    m_pan = p;
    NR51_REG = p;
  }
  if (m_state == M_OFF || !e) return;
  if (m_state == M_WAIT) {
    if (m_t > e) {
      m_t -= e;
      return;
    }
    song_start(m_want);
    row_tick();
    return;
  }
  /* fade ramps belong to song changes, independently of effects */
  k = m_gain;
  if (m_gain != m_goal && (m_rt = m_rt > e ? (uint8_t)(m_rt - e) : 0u) == 0u) {
    m_rt = m_rate;
    if (m_gain < m_goal)
      m_gain++;
    else
      m_gain--;
    k = 255u;
  }
  if (k != m_gain) {
    set_k();
    if (m_bassl && !wave_left) NR32_REG = wave_level(m_bassl);
  } /* the held bass follows the volume */
  /* rows keep the screen's time (VBlanks): a slow main-loop frame (art decoding) plays the rows it owes */
  m_clock = (uint8_t)(m_clock + e);
  while (m_clock >= m_frames && m_state != M_OFF) {
    m_clock -= m_frames;
    row_tick();
  }
  if (m_clock >= m_frames) m_clock = 0;
}
void music_mood(uint8_t m) BANKED {
  if (m == mood) return;
  mood = m;
  music_go();
}
/* The screen picks the song (merge and reveal keep the one playing); the clock and the story refine it. */
void music_scene(uint8_t scene) BANKED {
  if (scene == 1u || scene == 2u) return;
  m_scene = scene;
  fade_to(pick_song(1));
}
/* Settings: MUSIC and SFX volumes 0..8 (crucible_volume.h), read from the options byte and the core's flags. */
void sound_options(uint8_t o) BANKED {
  uint8_t ch;
  m_vol = vol_music(o);
  s_vol = vol_sfx(o, core.flags);
  sfx_off = (uint8_t)!s_vol;
  music_level = m_vol > 2u ? 0u
                : m_vol    ? 1u
                           : 2u; /* the effects' own wave cues: softer with soft music, none with none */
  set_k();
  if (m_bassl && m_state != M_OFF && !wave_left) NR32_REG = wave_level(m_bassl);
  music_go();
  if (sfx_off) {
    for (ch = 0; ch < 3u; ch++) {
      if (at[ch]) {
        at[ch] = 0;
        silence(ch);
      }
    }
  }
}
/* ---- voices: a motif per object, a timbre per category ---- */
static const uint8_t duty_of[7] = {2, 1, 2, 0, 1, 3, 2}, env_of[7] = {0x73, 0x62, 0x63, 0x81, 0x64, 0x71, 0x64};
static uint8_t motif(uint16_t id, uint8_t k) {
  uint16_t h = (uint16_t)id * 0x9e37u + k * 0x7f4au;
  h ^= h >> 7;
  h *= 0x2c1bu;
  h ^= h >> 9;
  return workshop_scale[h % 5u];
}
static void voice_list(uint8_t ch, uint16_t id, uint8_t category, uint8_t from, uint8_t count, uint8_t base,
                       uint8_t len, uint8_t hold) {
  uint8_t i, *o = vbuf[ch], note, duty = duty_of[category % 7u], env = env_of[category % 7u];
  uint16_t hz;
  for (i = 0; i < count && i < 7u; i++) {
    note = root + base + motif(id, (uint8_t)(from + i));
    if (note > 47u) note = 47u;
    hz = notes[note];
    *o++ = (uint8_t)(i + 1u == count ? hold : len);
    *o++ = i + 1u == count && hold > len ? (uint8_t)((env & 0xf0u) | 0x05u) : env;
    *o++ = (uint8_t)hz;
    *o++ = (uint8_t)((duty << 6) | (hz >> 8));
  }
  *o = 0;
  at[ch] = vbuf[ch];
  start(ch);
}
/* kind: 0 focus, 1 pick, 2 new discovery fanfare, 3 new recipe, 4 known, 5 swap step (from = step), 7 a talking
 * character's blip per typed letter (id = the character's voice; from: bits 0-2 the letter, 3-4 the pitch band, 5-6
 * the blip's length: every speaker sounds its own) */
void sound_voice(uint16_t id, uint8_t category, uint8_t kind, uint8_t from) BANKED {
  if (sfx_off) return;
  pitch = 0;
  /* the music has its own deterministic stream: actions colour upcoming notes and section choices */
  m_seed ^= (uint16_t)(id * 0x9e37u) ^ ((uint16_t)category << 8) ^ kind;
  if (!m_seed) m_seed = 1u;
  reaction_left = kind == 2u ? 192u : 96u;
  reaction_octave = kind == 2u || (motif(id, from) & 1u) ? 12u : 0u;
  /* 25% or 50%: the score's own duties (music STYLE.md: never 12.5% or 75%) */
  reaction_duty = (category & 1u) ? 1u : 2u;
  if (kind == 0u)
    voice_list(0, id, category, 0, 1, 12, 4, 4);
  else if (kind == 1u)
    voice_list(0, id, category, 0, 2, 12, 4, 8);
  else if (kind == 2u) {
    /* a single pulse fanfare leaves the score's melody and bass playing */
    voice_list(0, id, category, 0, 4, 12, 9, 36);
  } else if (kind == 3u)
    voice_list(0, id, category, 0, 3, 12, 6, 16);
  else if (kind == 4u)
    voice_list(0, id, category, 0, 2, 12, 5, 10);
  else if (kind == 5u)
    voice_list(0, id, category, from & 3u, 1, (uint8_t)(12u + ((from >> 2) & 1u) * 12u), 3, 3);
  else if (kind == 7u) {
    uint8_t l = (uint8_t)(1u + ((from >> 5) & 3u));
    voice_list(0u, id, category, from & 7u, 1, (uint8_t)(12u + ((from >> 3) & 3u) * 6u), l, l);
  } else { /* feat chime: rising modal notes, one note longer per tier */
    uint8_t i, *o = vbuf[0];
    uint16_t hz;
    for (i = 0; i < from + 3u && i < 6u; i++) {
      hz = notes[root + 24u + workshop_scale[i % 5u] + (i / 5u) * 12u];
      *o++ = i + 1u == from + 3u ? 20u : 5u;
      *o++ = 0x83u;
      *o++ = (uint8_t)hz;
      *o++ = (uint8_t)((1u << 6) | (hz >> 8));
    }
    *o = 0;
    at[0] = vbuf[0];
    start(0);
  }
}
void sound_init(void) BANKED {
  NR52_REG = 0x80u;
  NR50_REG = 0x77u;
  NR51_REG = 0xffu;
  at[0] = at[1] = at[2] = 0;
  pitch = 0;
  m_s = 0;
  m_state = M_OFF;
  wave_left = 0;
  reaction_left = reaction_octave = reaction_duty = 0;
  m_bassl = 0;
  m_gain = G_FULL;
  m_span = 0xffu;
  m_wave = 255u;
  m_pan = 0xffu;
  load_wave(KM_WAVE_PAD);
  NR32_REG = 0;
  mood = 0;
  music_force = 255u;
  m_heard = 0;
  m_scene = 5u;
  m_want = SONG_TITLE_PUNCH;
  seed = core.rng | 1u;
  sound_options(core.options);
  root = (uint8_t)(rnd() % 5u);
  root = root == 0u ? 0u : root == 1u ? 2u : root == 2u ? 5u : root == 3u ? 7u : 9u;
  m_last = sys_time;
  m_seed = (uint16_t)(core.rng ^ 0x6d2bu) | 1u;
}
void sound_pitch(uint8_t p) BANKED { pitch = p; }
static void effect_list(uint8_t ch, const uint8_t *n) {
  uint8_t i, note, *o = vbuf[ch];
  uint16_t hz;
  for (i = 0; n[0] && i < 7u; i++, n += 4) {
    note = (uint8_t)(root + n[2]);
    if (note > 47u) note = 47u;
    hz = notes[note];
    *o++ = n[0];
    *o++ = n[1];
    *o++ = (uint8_t)hz;
    *o++ = (uint8_t)(n[3] | (hz >> 8));
  }
  *o = 0;
  at[ch] = vbuf[ch];
  start(ch);
}
void sound_play(uint8_t id) BANKED {
  const sfx_t *s;
  if (sfx_off || id >= sizeof(table) / sizeof(table[0])) return;
  s = &table[id];
  if (id != SFX_SWAP) pitch = 0;
  if (s->ch1) effect_list(0, s->ch1);
  if (s->ch2) effect_list(1, s->ch2);
  if (s->ch4) {
    at[2] = s->ch4;
    start(2);
  }
}
/* Fusion climbs through the same mode as the ingredients, with a finite tail. */
void sound_drone(uint8_t step) BANKED {
  if (sfx_off) return;
  /* the ingredient answers the bass without taking the bass channel */
  voice_list(0, step, reaction_duty, step >> 1, 1, 0, 3, 3);
  reaction_left = 96u;
  m_seed ^= (uint16_t)(step + 1u) << 8;
}
void sound_tick(void) BANKED {
  uint8_t ch, elapsed = (uint8_t)(sys_time - m_last), e;
  if (elapsed > 8u) elapsed = 8u;
  for (ch = 0; ch < 3u; ch++) {
    e = elapsed;
    while (at[ch] && e >= left[ch]) {
      e -= left[ch];
      at[ch] += 4;
      start(ch);
    }
    if (at[ch]) left[ch] -= e;
  }
  music_tick();
}
