#ifndef CRUCIBLE_DATA_H
#define CRUCIBLE_DATA_H
#include <gb/gb.h>
/* Generated by the art toolchain (not part of this repository); do not edit. Object ids are stable: new objects are appended. */
#define CRUCIBLE_PROGRAM_MAX 2880u
#define CRUCIBLE_ITEMS 5629u
#define CRUCIBLE_RECIPES 13439u
#define CRUCIBLE_STARTER_COUNT 4u
#define CRUCIBLE_CATEGORIES 7u
/* crucible_art modes: VRAM bank 1, sprite tiles, capture into fusion scratch; low bits 1..24 form a revealed silhouette. */
#define CRUCIBLE_ART_BANK1 0x40u
#define CRUCIBLE_ART_SPRITE 0x20u
#define CRUCIBLE_ART_CAPTURE 0x80u
#define CRUCIBLE_ART_FORM 0x1fu
extern uint16_t crucible_shade_mask;
void crucible_get_fingerprint(uint8_t*) BANKED;
#define CRUCIBLE_ART_STAMP 0xc30a5289ul   /* the art build: a cache that outlives power-off must match it */
void crucible_load_font(void) BANKED;
/* Object art (crucible_art.c): show frame index of object id's resting loop (turn 0, index = pose) or turntable
 * (turn 1, index = view step) from stream slot 0..CRUCIBLE_ART_SLOTS-1 (one per animated bench cell), or just the
 * keyframe without a stream (CRUCIBLE_ART_KEY). */
#define CRUCIBLE_VIEWS 12u
#define CRUCIBLE_POSES 8u
#define CRUCIBLE_ART_SLOTS 4u
#define CRUCIBLE_ART_KEY 255u
uint8_t crucible_art(uint8_t slot,uint16_t id,uint8_t turn,uint8_t index,uint8_t variant,uint8_t tile,uint8_t palette,uint8_t mode) BANKED;
/* once per main-loop frame (decode budgets); which frame index the last crucible_art call drew */
void crucible_art_tick(void) BANKED;
extern uint8_t crucible_art_shown;
void crucible_emit(uint8_t tile,uint8_t mode) BANKED;
uint16_t crucible_art_locate(uint16_t,const uint8_t**) BANKED;
uint8_t crucible_frame_ticks(uint16_t) BANKED;
#define CRUCIBLE_BUSTS 20u
#define CRUCIBLE_MARBLE_BUSTS 4u
void crucible_bust_palette(uint8_t b,uint16_t*out) BANKED;
void crucible_bust(uint8_t b,uint8_t view,uint8_t chunk,uint8_t tile,uint8_t bank) BANKED;
void crucible_get_name(uint16_t,char*) BANKED;
void crucible_get_category(uint16_t,char*) BANKED;
void crucible_category_name(uint8_t,char*) BANKED;
/* traits mask: bit order HOT COLD WET AIRY STONE SHINY GLOWS ALIVE GREEN MADE BIG MAGIC */
uint16_t crucible_traits(uint16_t) BANKED;
#define CRUCIBLE_TRAITS 12u
/* recipes, starters, shelf order and the rules live in the CRUCIBLE core (crucible_core_tables.c) */
uint8_t crucible_category(uint16_t) BANKED;
void crucible_get_palette(uint16_t,uint8_t,uint16_t*) BANKED;
#endif
