/* Generated by the asset toolchain (not part of this repository); do not edit. Included by crucible_eggs.c only. */
#define EGG_COUNT 18u
static const uint8_t egg_kind[]={0,1,2,3,4,4,4,4,4,4,4,4,4,5,5,5,5,6};
static const uint16_t egg_arg[]={0,8,180,3,3758,2408,735,40,649,276,430,652,47,0,1,2,3,5};
static const uint16_t egg_line[]={434,437,440,442,444,447,449,451,453,455,457,459,461,463,465,467,469,471};
static const uint8_t egg_nlines[]={3,3,2,2,3,2,2,2,2,2,2,2,2,2,2,2,2,2};
static const uint8_t egg_fac[]={0,5,5,5,4,3,3,5,5,1,2,4,5,4,4,2,4,2};
static const uint8_t egg_flags[]={0,2,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,1};
static const uint16_t egg_grant[]={582,65535,65535,65535,65535,65535,65535,65535,65535,65535,65535,65535,632,65535,65535,4369,65535,65535};
static const char egg_visitor[][11]={"CONTRA.EXE","DMG-01","ATTRACT","CARTRIDGE","KNOCKKNOCK","CHILD.EXE","GLADYS","TOAD.SYS","ARCADIA","BLUR","CLYDE","PLUMBER","OLD MAN","MORPHEUS","OPERATOR","MISSINGNO.","PROF.OAK","GROUNDHOG"};
static const uint8_t egg_codes[][12]={{4,4,8,8,2,1,2,1,32,16,0}};
static const char egg_names[][9]={"NEO","TRINITY","MISSINGN","RED"};
