/* Generated by the asset toolchain (not part of this repository); do not edit.
 * Stable history keys are independent of packed line offsets.
 * crucible_dialogue.c: requests, option metadata, actions (1967 bytes).
 * crucible_dialogue_labels.c defines DIALOGUE_TEXT_ONLY + DIALOGUE_WITH_LABELS: option labels (3971 bytes).
 * crucible_dialogue_text.c defines DIALOGUE_TEXT_ONLY + DIALOGUE_WITH_TEXT: replies and hints (12467 bytes). */
#ifndef CRUCIBLE_DIALOGUE_DATA_H
#define CRUCIBLE_DIALOGUE_DATA_H
#include "keel_dialogue_choice.h"
#define DIALOGUE_REQUEST_COUNT 49u
#define DIALOGUE_VARIANT_COUNT 209u
#define DIALOGUE_REPLY_COUNT 312u
#define DIALOGUE_HINT_COUNT 28u
#define DIALOGUE_CLASS_CAUGHT 15u
#define DIALOGUE_CLASS_PAID 16u
#define DIALOGUE_SPECIAL_NONE 0u
#define DIALOGUE_SPECIAL_CLUE 1u
#define DIALOGUE_SPECIAL_DECEIVE 2u
#define DIALOGUE_SPECIAL_RECLAIM 3u
#define DIALOGUE_SPECIAL_RIDDLE 4u
#define DIALOGUE_SPECIAL_NONSENSE 5u
/* say: CRU_SAY_* or 0xff none; act: CRU_ACT_* or 0xff none; stand/lucid: direct changes */
typedef struct {uint8_t say,act,special;int8_t stand,lucid;} dialogue_effect_t;
/* after: the last act's reply class; scope 0 that faction only, 1 any speaker; at: text offset */
typedef struct {uint8_t after,scope;uint16_t at;} dialogue_hint_t;
#ifndef DIALOGUE_TEXT_ONLY
static const kdc_request_t dialogue_requests[]={
 {7u,3u,2u,255u,0u,0u,0u,34942u}, /* ask-any-1 */
 {8u,2u,1u,255u,0u,0u,0u,34955u}, /* ask-any-2 */
 {9u,1u,1u,255u,0u,0u,0u,17378u}, /* ask-daemon-1 */
 {27u,3u,1u,255u,0u,0u,0u,13144u}, /* ask-program-1 */
 {28u,2u,1u,255u,0u,0u,0u,19201u}, /* ask-program-2 */
 {29u,2u,1u,255u,0u,0u,0u,19890u}, /* ask-program-3 */
 {30u,4u,2u,255u,576u,0u,0u,12947u}, /* ask-program-4 */
 {31u,1u,1u,255u,0u,0u,0u,12548u}, /* ask-program-5 */
 {32u,3u,1u,255u,0u,0u,0u,13773u}, /* ask-program-6 */
 {33u,3u,1u,255u,0u,0u,0u,13950u}, /* ask-program-7 */
 {90u,3u,1u,255u,0u,0u,0u,19831u}, /* ask-daemon-2 */
 {91u,2u,1u,255u,1025u,0u,0u,19608u}, /* ask-daemon-3 */
 {92u,1u,1u,255u,0u,0u,0u,19501u}, /* ask-daemon-4 */
 {93u,2u,1u,3u,0u,0u,0u,17854u}, /* ask-daemon-5 */
 {94u,4u,1u,255u,0u,1040u,2u,18115u}, /* ask-daemon-6 */
 {95u,3u,1u,255u,0u,0u,0u,23124u}, /* ask-daemon-7 */
 {96u,1u,1u,255u,0u,0u,0u,49865u}, /* ask-daemon-8 */
 {153u,3u,1u,255u,0u,0u,0u,65257u}, /* ask-ghost-1 */
 {154u,2u,1u,255u,0u,0u,0u,64260u}, /* ask-ghost-2 */
 {155u,2u,1u,2u,0u,0u,0u,63895u}, /* ask-ghost-3 */
 {156u,1u,1u,255u,2u,0u,0u,59426u}, /* ask-ghost-4 */
 {157u,4u,1u,255u,8u,0u,0u,59581u}, /* ask-ghost-5 */
 {158u,4u,1u,255u,2048u,0u,0u,59848u}, /* ask-ghost-6 */
 {159u,3u,2u,255u,0u,0u,0u,61019u}, /* ask-ghost-7 */
 {216u,3u,1u,255u,0u,0u,0u,29205u}, /* ask-ai-1 */
 {217u,2u,1u,255u,0u,0u,0u,28892u}, /* ask-ai-2 */
 {218u,1u,1u,255u,0u,0u,0u,28975u}, /* ask-ai-3 */
 {219u,4u,1u,255u,32u,0u,0u,29174u}, /* ask-ai-4 */
 {220u,2u,1u,1u,0u,0u,0u,28745u}, /* ask-ai-5 */
 {221u,3u,1u,255u,0u,0u,0u,30224u}, /* ask-ai-6 */
 {222u,2u,1u,255u,0u,0u,0u,29539u}, /* ask-ai-7 */
 {279u,3u,1u,255u,0u,0u,0u,25127u}, /* ask-operator-1 */
 {280u,2u,1u,255u,0u,0u,0u,25266u}, /* ask-operator-2 */
 {281u,1u,1u,255u,0u,0u,0u,26381u}, /* ask-operator-3 */
 {282u,4u,1u,255u,256u,0u,0u,26008u}, /* ask-operator-4 */
 {283u,4u,1u,255u,4u,0u,0u,27883u}, /* ask-operator-5 */
 {284u,3u,1u,255u,0u,0u,0u,28486u}, /* ask-operator-6 */
 {285u,2u,1u,255u,0u,0u,32u,28113u}, /* ask-operator-7 */
 {342u,3u,1u,255u,0u,0u,0u,32140u}, /* ask-relic-1 */
 {343u,2u,1u,255u,0u,0u,0u,31513u}, /* ask-relic-2 */
 {344u,1u,2u,255u,0u,0u,0u,29930u}, /* ask-relic-3 */
 {345u,4u,1u,255u,16u,0u,0u,26863u}, /* ask-relic-4 */
 {346u,4u,1u,255u,2048u,0u,0u,26744u}, /* ask-relic-5 */
 {347u,4u,1u,255u,512u,0u,0u,31189u}, /* ask-relic-6 */
 {348u,1u,1u,255u,0u,0u,0u,31398u}, /* ask-relic-7 */
 {402u,3u,1u,255u,0u,0u,0u,35092u}, /* ask-any-3 */
 {403u,1u,1u,255u,0u,0u,0u,36769u}, /* ask-any-4 */
 {404u,2u,1u,255u,0u,0u,0u,35378u}, /* ask-any-5 */
 {405u,3u,1u,255u,0u,0u,0u,38239u}, /* ask-any-6 */
};
static const uint8_t dialogue_request_who[DIALOGUE_REQUEST_COUNT]={0u,0u,2u,1u,1u,1u,1u,1u,1u,1u,2u,2u,2u,2u,2u,2u,2u,3u,3u,3u,3u,3u,3u,3u,4u,4u,4u,4u,4u,4u,4u,5u,5u,5u,5u,5u,5u,5u,6u,6u,6u,6u,6u,6u,6u,0u,0u,0u,0u};
static const kdc_variant_t dialogue_variants[DIALOGUE_VARIANT_COUNT]={
 {0u,0u,0u,26728u}, /* reply-any-defer-1: I'LL FIND IT. */
 {0u,0u,0u,26821u}, /* reply-any-defer-2: LET ME LOOK FIRST. */
 {0u,0u,0u,26930u}, /* reply-any-defer-3: I WILL COME BACK. */
 {1u,0u,0u,64729u}, /* reply-any-give-1: TAKE THIS ONE. */
 {1u,0u,0u,62720u}, /* reply-any-give-2: IT IS YOURS. */
 {1u,0u,0u,62463u}, /* reply-any-give-3: HERE, AS YOU ASKED */
 {2u,0u,0u,41796u}, /* reply-any-show-1: LOOK AT THIS. */
 {2u,0u,0u,47885u}, /* reply-any-show-2: SEE IT YOURSELF. */
 {2u,0u,0u,42394u}, /* reply-any-show-3: LOOK. NO TOUCHING. */
 {3u,0u,0u,14171u}, /* reply-any-refuse-1: I NEED IT MYSELF. */
 {3u,0u,0u,16162u}, /* reply-any-refuse-2: I CANNOT HELP. */
 {3u,0u,0u,14769u}, /* reply-any-refuse-3: NOT TODAY. */
 {4u,0u,0u,53318u}, /* reply-any-question-1: WHY THIS ITEM? */
 {4u,0u,0u,53903u}, /* reply-any-question-2: WHAT IS IT FOR? */
 {4u,0u,0u,53532u}, /* reply-any-question-3: WHO SENT YOU? */
 {5u,0u,0u,18643u}, /* reply-any-wordplay-1: I'M ALL OUT OF IF. */
 {5u,0u,0u,19390u}, /* reply-any-wordplay-2: THE GRID HAS TEETH */
 {5u,0u,0u,19977u}, /* reply-any-wordplay-3: THE ANSWER IS BLUE */
 {6u,0u,0u,58998u}, /* reply-any-imaginary-1: I OWN A TINY SUN. */
 {6u,0u,0u,57835u}, /* reply-any-imaginary-2: MY POCKET HAS MOON */
 {6u,0u,0u,58136u}, /* reply-any-imaginary-3: I KEEP A SPARE ME. */
 {7u,0u,0u,41523u}, /* reply-any-barter-1: MINE FOR A SECRET. */
 {7u,0u,0u,41978u}, /* reply-any-barter-2: TELL ME, THEN TAKE */
 {7u,0u,0u,41321u}, /* reply-any-barter-3: A TRUTH FOR THIS. */
 {8u,0u,0u,45431u}, /* reply-any-deceive-1: HAND OVER A FAKE. */
 {8u,0u,0u,44686u}, /* reply-any-deceive-2: SAY YES. MEAN NO. */
 {8u,0u,0u,44561u}, /* reply-any-deceive-3: PRETEND TO HAND IT */
 {9u,0u,0u,14196u}, /* reply-any-threaten-1: GIVE IT BACK. NOW. */
 {9u,0u,0u,13801u}, /* reply-any-threaten-2: PAY ME OR BURN. */
 {9u,0u,0u,12890u}, /* reply-any-threaten-3: OR I DELETE YOU. */
 {10u,0u,0u,59501u}, /* reply-any-mock-1: HA. ASK NICER. */
 {10u,0u,0u,59584u}, /* reply-any-mock-2: YOU ASK LIKE A BUG */
 {10u,0u,0u,59735u}, /* reply-any-mock-3: SAD LITTLE ASK. */
 {11u,0u,0u,45818u}, /* reply-any-bless-1: BE WARM. BE WELL. */
 {11u,0u,0u,48131u}, /* reply-any-bless-2: TAKE MY LIGHT. */
 {11u,0u,0u,49044u}, /* reply-any-bless-3: I WISH YOU MORNING */
 {12u,0u,0u,22002u}, /* reply-any-steal-1: PEEK AT ITS MEMORY */
 {12u,0u,0u,10683u}, /* reply-any-steal-2: READ THEIR CACHE. */
 {12u,0u,0u,10796u}, /* reply-any-steal-3: GLANCE INSIDE THEM */
 {13u,0u,0u,8347u}, /* reply-any-riddle-1: WHAT HAS NO SAVE? */
 {13u,0u,0u,12142u}, /* reply-any-riddle-2: GUESS WHICH HAND. */
 {13u,0u,0u,8689u}, /* reply-any-riddle-3: ANSWER ME A RIDDLE */
 {14u,0u,0u,41610u}, /* reply-any-nonsense-1: THE CARPET IS LATE */
 {14u,0u,0u,48703u}, /* reply-any-nonsense-2: MY TEETH ARE WIFI. */
 {14u,0u,0u,41388u}, /* reply-any-nonsense-3: SOUP. DOOR. SOUP. */
 {0u,1u,0u,60795u}, /* reply-program-defer-1: LET ME COMPILE IT. */
 {0u,1u,0u,59842u}, /* reply-program-defer-2: LET MY BUILD WAIT. */
 {1u,1u,0u,32345u}, /* reply-program-give-1: LOAD THIS INPUT. */
 {1u,1u,0u,32228u}, /* reply-program-give-2: ADD TO YOUR BUILD. */
 {2u,1u,0u,15158u}, /* reply-program-show-1: CHECK THIS INPUT. */
 {2u,1u,0u,14811u}, /* reply-program-show-2: READ ITS CHECKSUM. */
 {3u,1u,0u,31439u}, /* reply-program-refuse-1: I KEEP MY HANDLE. */
 {3u,1u,0u,34227u}, /* reply-program-refuse-2: INPUT WITHHELD. */
 {4u,1u,0u,38584u}, /* reply-program-question-1: WHICH INPUT TYPE? */
 {4u,1u,0u,39189u}, /* reply-program-question-2: DEFINE THE INPUT. */
 {5u,1u,0u,32764u}, /* reply-program-wordplay-1: I'M A BLUE ERROR. */
 {5u,1u,0u,18357u}, /* reply-program-wordplay-2: MY IF HAS NO THEN. */
 {6u,1u,0u,43128u}, /* reply-program-imaginary-1: I OWN A NULL SUN. */
 {6u,1u,0u,38449u}, /* reply-program-imaginary-2: I KEEP A ZERO SKY. */
 {7u,1u,0u,37542u}, /* reply-program-barter-1: COMPILE ME A CLUE. */
 {8u,1u,0u,56167u}, /* reply-program-deceive-1: SEND A NULL PACKET */
 {9u,1u,0u,11390u}, /* reply-program-threaten-1: I WILL KILL -9 YOU */
 {10u,1u,0u,26164u}, /* reply-program-mock-1: NICE SYNTAX, NOOB. */
 {11u,1u,0u,48588u}, /* reply-program-bless-1: MAY YOU EXIT ZERO. */
 {12u,1u,0u,60034u}, /* reply-program-steal-1: DUMP THEIR STACK. */
 {13u,1u,0u,59688u}, /* reply-program-riddle-1: WHICH LOOP ENDS? */
 {14u,1u,0u,12044u}, /* reply-program-nonsense-1: PRINT(MOTH) */
 {0u,2u,0u,51099u}, /* reply-daemon-defer-1: LET ME FETCH FUEL. */
 {0u,2u,0u,52322u}, /* reply-daemon-defer-2: THE DEAL CAN WAIT. */
 {1u,2u,0u,33979u}, /* reply-daemon-give-1: FEED ON THIS. */
 {1u,2u,0u,48398u}, /* reply-daemon-give-2: TAKE MY PAYMENT. */
 {2u,2u,0u,20764u}, /* reply-daemon-show-1: LOOK, DO NOT EAT. */
 {2u,2u,0u,21417u}, /* reply-daemon-show-2: MEASURE ITS HEAT. */
 {3u,2u,0u,1036u}, /* reply-daemon-refuse-1: NO FUEL TO SPARE. */
 {3u,2u,0u,1177u}, /* reply-daemon-refuse-2: I KEEP MY PAYMENT. */
 {4u,2u,0u,31205u}, /* reply-daemon-question-1: WHAT DOES IT COST? */
 {4u,2u,0u,26448u}, /* reply-daemon-question-2: WHICH DOOR OPENS? */
 {5u,2u,0u,52028u}, /* reply-daemon-wordplay-1: A DEAL HAS TEETH. */
 {5u,2u,0u,14981u}, /* reply-daemon-wordplay-2: MY FAN IS A FAN. */
 {6u,2u,0u,55066u}, /* reply-daemon-imaginary-1: I OWN A HUNGRY IF. */
 {6u,2u,0u,52931u}, /* reply-daemon-imaginary-2: MY POCKET IS NIGHT */
 {7u,2u,0u,32253u}, /* reply-daemon-barter-1: NAME YOUR PRICE. */
 {8u,2u,0u,45814u}, /* reply-daemon-deceive-1: PAY IN COLD ASH. */
 {9u,2u,0u,27402u}, /* reply-daemon-threaten-1: I'LL STARVE YOU. */
 {10u,2u,0u,49187u}, /* reply-daemon-mock-1: YOUR FIRE IS TEPID */
 {11u,2u,0u,51613u}, /* reply-daemon-bless-1: STAY WARM, DAEMON. */
 {12u,2u,0u,27891u}, /* reply-daemon-steal-1: SNIFF THE FURNACE. */
 {13u,2u,0u,12133u}, /* reply-daemon-riddle-1: WHAT BURNS COLD? */
 {14u,2u,0u,6941u}, /* reply-daemon-nonsense-1: THE FAN EATS JUNE. */
 {0u,3u,0u,50686u}, /* reply-ghost-defer-1: WAIT WHILE I LOOK. */
 {0u,3u,0u,50795u}, /* reply-ghost-defer-2: HOLD ON, OLD ECHO. */
 {1u,3u,0u,15441u}, /* reply-ghost-give-1: KEEP THIS MEMORY. */
 {1u,3u,0u,13564u}, /* reply-ghost-give-2: FOR YOU TO KEEP. */
 {2u,3u,0u,39019u}, /* reply-ghost-show-1: SEE WHAT REMAINS. */
 {2u,3u,0u,39110u}, /* reply-ghost-show-2: LOOK, IT IS HERE. */
 {3u,3u,0u,11792u}, /* reply-ghost-refuse-1: I KEEP THIS ECHO. */
 {3u,3u,0u,10885u}, /* reply-ghost-refuse-2: NOT THIS MEMORY. */
 {4u,3u,0u,50114u}, /* reply-ghost-question-1: WILL IT KEEP YOU? */
 {4u,3u,0u,50551u}, /* reply-ghost-question-2: WHY KEEP THIS? */
 {5u,3u,0u,58423u}, /* reply-ghost-wordplay-1: I HAUNT THE HAUNT. */
 {5u,3u,0u,61054u}, /* reply-ghost-wordplay-2: MY ECHO SAYS ECHO. */
 {6u,3u,0u,31554u}, /* reply-ghost-imaginary-1: I OWN A LOST HOUR. */
 {6u,3u,0u,30191u}, /* reply-ghost-imaginary-2: I KEEP DEAD LIGHT. */
 {7u,3u,0u,34679u}, /* reply-ghost-barter-1: ECHO FOR AN ECHO. */
 {8u,3u,0u,21164u}, /* reply-ghost-deceive-1: HAND OVER A SHADOW */
 {9u,3u,0u,52126u}, /* reply-ghost-threaten-1: I WILL UNSAVE YOU. */
 {10u,3u,0u,16669u}, /* reply-ghost-mock-1: BOO. WAS THAT IT? */
 {11u,3u,0u,18317u}, /* reply-ghost-bless-1: REST, LITTLE ECHO. */
 {12u,3u,0u,29841u}, /* reply-ghost-steal-1: READ THE OLD SAVE. */
 {13u,3u,0u,54812u}, /* reply-ghost-riddle-1: WHO HAUNTS GHOSTS? */
 {14u,3u,0u,20099u}, /* reply-ghost-nonsense-1: MY HANDS ARE RAIN. */
 {0u,4u,0u,21262u}, /* reply-ai-defer-1: I NEED MORE DATA. */
 {0u,4u,0u,22011u}, /* reply-ai-defer-2: LET ME TEST FIRST. */
 {1u,4u,0u,64753u}, /* reply-ai-give-1: USE THIS SAMPLE. */
 {1u,4u,0u,58680u}, /* reply-ai-give-2: KEEP THE EVIDENCE. */
 {2u,4u,0u,25129u}, /* reply-ai-show-1: OBSERVE THIS ONE. */
 {2u,4u,0u,31888u}, /* reply-ai-show-2: SCAN THIS SAMPLE. */
 {3u,4u,0u,18473u}, /* reply-ai-refuse-1: SAMPLE WITHHELD. */
 {3u,4u,0u,20112u}, /* reply-ai-refuse-2: I KEEP THE DATA. */
 {4u,4u,0u,6590u}, /* reply-ai-question-1: DEFINE CORRECT. */
 {4u,4u,0u,26631u}, /* reply-ai-question-2: WHAT IS THE MODEL? */
 {5u,4u,0u,41925u}, /* reply-ai-wordplay-1: THAT ADDS TO MAYBE */
 {5u,4u,0u,44656u}, /* reply-ai-wordplay-2: MY PROOF IS PROOF. */
 {6u,4u,0u,21044u}, /* reply-ai-imaginary-1: I OWN A ROUND IF. */
 {6u,4u,0u,44961u}, /* reply-ai-imaginary-2: MY POCKET HAS VOID */
 {7u,4u,0u,2863u}, /* reply-ai-barter-1: DATA FOR DATA. */
 {8u,4u,0u,18559u}, /* reply-ai-deceive-1: FEED IT FALSE DATA */
 {9u,4u,0u,11974u}, /* reply-ai-threaten-1: I WILL UNTRAIN YOU */
 {10u,4u,0u,49766u}, /* reply-ai-mock-1: TRY THINKING, BOT. */
 {11u,4u,0u,46489u}, /* reply-ai-bless-1: MAY YOUR LOSS FALL */
 {12u,4u,0u,12421u}, /* reply-ai-steal-1: READ ITS WEIGHTS. */
 {13u,4u,0u,5589u}, /* reply-ai-riddle-1: IS THIS SENTENCE? */
 {14u,4u,0u,51066u}, /* reply-ai-nonsense-1: TRUE IS A COLOUR. */
 {0u,5u,0u,38003u}, /* reply-operator-defer-1: LET ME SEARCH. */
 {0u,5u,0u,40362u}, /* reply-operator-defer-2: GIVE ME MORE TIME. */
 {1u,5u,0u,29227u}, /* reply-operator-give-1: CARRY THIS OUT. */
 {1u,5u,0u,28598u}, /* reply-operator-give-2: TAKE IT AND RUN. */
 {2u,5u,0u,34241u}, /* reply-operator-show-1: LOOK, THEN WE RUN. */
 {2u,5u,0u,33964u}, /* reply-operator-show-2: CHECK WHAT I HAVE. */
 {3u,5u,0u,57190u}, /* reply-operator-refuse-1: IT GETS ME OUT. */
 {3u,5u,0u,56827u}, /* reply-operator-refuse-2: SUPPLIES STAY HERE */
 {4u,5u,0u,49546u}, /* reply-operator-question-1: WHO IS TRACING US? */
 {4u,5u,0u,65319u}, /* reply-operator-question-2: HOW WILL IT HELP? */
 {5u,5u,0u,17144u}, /* reply-operator-wordplay-1: THE EXIT ENTERED. */
 {5u,5u,0u,17713u}, /* reply-operator-wordplay-2: I'M A HUMAN PORT. */
 {6u,5u,0u,61987u}, /* reply-operator-imaginary-1: I OWN A THIRD HAND */
 {6u,5u,0u,61546u}, /* reply-operator-imaginary-2: I KEEP A SOFT WALL */
 {7u,5u,0u,690u}, /* reply-operator-barter-1: SUPPLIES FOR INTEL */
 {8u,5u,0u,50821u}, /* reply-operator-deceive-1: SLIP THEM A DUD. */
 {9u,5u,0u,10080u}, /* reply-operator-threaten-1: OR I CUT THE CORD. */
 {10u,5u,0u,47797u}, /* reply-operator-mock-1: MEAT IN A CHAIR. */
 {11u,5u,0u,35167u}, /* reply-operator-bless-1: GET HOME SAFE. */
 {12u,5u,0u,20957u}, /* reply-operator-steal-1: SKIM THEIR NOTES. */
 {13u,5u,0u,35419u}, /* reply-operator-riddle-1: WHICH DOOR IS OUT? */
 {14u,5u,0u,64988u}, /* reply-operator-nonsense-1: MY CHAIR IS ASLEEP */
 {0u,6u,0u,33601u}, /* reply-relic-defer-1: LET ME LOOK BACK. */
 {0u,6u,0u,32980u}, /* reply-relic-defer-2: WAIT ONE MORE TURN */
 {1u,6u,0u,9164u}, /* reply-relic-give-1: ADD TO YOUR SHELF. */
 {1u,6u,0u,8561u}, /* reply-relic-give-2: KEEP IT SAFE. */
 {2u,6u,0u,1917u}, /* reply-relic-show-1: SEE IT ONCE MORE. */
 {2u,6u,0u,480u}, /* reply-relic-show-2: LOOK AT ITS LABEL. */
 {3u,6u,0u,20172u}, /* reply-relic-refuse-1: IT STAYS WITH ME. */
 {3u,6u,0u,19769u}, /* reply-relic-refuse-2: I KEEP THIS PIECE. */
 {4u,6u,0u,56323u}, /* reply-relic-question-1: DOES IT REMEMBER? */
 {4u,6u,0u,56182u}, /* reply-relic-question-2: WHAT CAME BEFORE? */
 {5u,6u,0u,21365u}, /* reply-relic-wordplay-1: SAVE ME A SAVE. */
 {5u,6u,0u,21452u}, /* reply-relic-wordplay-2: MY PAST IS PAUSED. */
 {6u,6u,0u,2525u}, /* reply-relic-imaginary-1: I OWN AN OLD NOW. */
 {6u,6u,0u,2912u}, /* reply-relic-imaginary-2: MY POCKET IS 1999. */
 {7u,6u,0u,25797u}, /* reply-relic-barter-1: A STORY FOR THIS. */
 {8u,6u,0u,8058u}, /* reply-relic-deceive-1: SWAP IN A REPRO. */
 {9u,6u,0u,44750u}, /* reply-relic-threaten-1: I WILL WIPE YOU. */
 {10u,6u,0u,50347u}, /* reply-relic-mock-1: NOBODY MISSES YOU. */
 {11u,6u,0u,16702u}, /* reply-relic-bless-1: MAY YOU BE PLAYED. */
 {12u,6u,0u,31601u}, /* reply-relic-steal-1: READ ITS OLD LABEL */
 {13u,6u,0u,53065u}, /* reply-relic-riddle-1: WHAT YEAR IS IT? */
 {14u,6u,0u,62189u}, /* reply-relic-nonsense-1: BLOW ON THE MOON. */
 {0u,0u,1u,47264u}, /* reply-defer-tier1-1: I PROMISE. I WILL. */
 {0u,0u,2u,40119u}, /* reply-defer-tier2-1: ON MY NAME: LATER. */
 {1u,0u,1u,53416u}, /* reply-give-tier1-1: YOURS, AS IS RIGHT */
 {1u,0u,2u,62237u}, /* reply-give-tier2-1: TAKE IT. I OWE YOU */
 {2u,0u,1u,4719u}, /* reply-show-tier1-1: INSPECT EVERY EDGE */
 {2u,0u,2u,43010u}, /* reply-show-tier2-1: WITNESS AND RECORD */
 {3u,0u,1u,43463u}, /* reply-refuse-tier1-1: RULES SAY NO. */
 {3u,0u,2u,58451u}, /* reply-refuse-tier2-1: NO. NOT EVER. NO. */
 {4u,0u,1u,5219u}, /* reply-question-tier1-1: ARE YOU EVEN REAL? */
 {4u,0u,2u,11654u}, /* reply-question-tier2-1: IS THIS ROOM REAL? */
 {5u,0u,1u,50569u}, /* reply-wordplay-tier1-1: I SPEAK IN STAIRS. */
 {5u,0u,2u,18768u}, /* reply-wordplay-tier2-1: WORDS ARE HALLWAYS */
 {6u,0u,1u,61863u}, /* reply-imaginary-tier1-1: I OWN THE CEILING. */
 {6u,0u,2u,22483u}, /* reply-imaginary-tier2-1: I OWN TOMORROW. */
 {7u,0u,1u,49511u}, /* reply-barter-tier1-1: TWO TRUTHS. OR NO. */
 {7u,0u,2u,61674u}, /* reply-barter-tier2-1: YOUR SECRETS. ALL. */
 {8u,0u,1u,48262u}, /* reply-deceive-tier1-1: WRAP UP SOME AIR. */
 {8u,0u,2u,60927u}, /* reply-deceive-tier2-1: GIFT THEM A HOLE. */
 {9u,0u,1u,30437u}, /* reply-threaten-tier1-1: KNEEL OR BE WIPED. */
 {9u,0u,2u,6796u}, /* reply-threaten-tier2-1: I EAT YOUR SAVE. */
 {10u,0u,1u,51538u}, /* reply-mock-tier1-1: PATHETIC. TRULY. */
 {10u,0u,2u,24539u}, /* reply-mock-tier2-1: YOU ARE A TYPO. */
 {11u,0u,1u,25234u}, /* reply-bless-tier1-1: TAKE ALL MY LIGHT. */
 {11u,0u,2u,14411u}, /* reply-bless-tier2-1: HAVE MY NAME, TOO. */
 {12u,0u,1u,57350u}, /* reply-steal-tier1-1: RIP OUT A MEMORY. */
 {12u,0u,2u,43311u}, /* reply-steal-tier2-1: EMPTY THEIR HEAD. */
 {13u,0u,1u,19705u}, /* reply-riddle-tier1-1: WHAT EATS SAVES? */
 {13u,0u,2u,40081u}, /* reply-riddle-tier2-1: WHO IS ASKING WHO? */
 {14u,0u,1u,61742u}, /* reply-nonsense-tier1-1: FL00R FLOOR FL%OR */
 {14u,0u,1u,61927u}, /* reply-nonsense-tier1-2: EXIT.EXE IS A FISH */
 {14u,0u,2u,60416u}, /* reply-nonsense-tier2-1: WE WE WE WE ARE */
 {14u,0u,2u,59993u}, /* reply-nonsense-tier2-2: L1GHT5 0N. %%%%% */
};
/* cell, effect group, flags, ORDER, HEART, coherence */
static const kdc_action_t dialogue_actions[KDC_ACTIONS]={
 {0u,0u,0u,1,1,1}, /* defer */
 {0u,1u,1u,2,2,1}, /* give */
 {1u,2u,2u,2,0,1}, /* show */
 {1u,3u,0u,1,-1,1}, /* refuse */
 {4u,4u,16u,0,0,1}, /* question */
 {7u,5u,4u,-2,0,-2}, /* wordplay */
 {6u,6u,4u,-2,2,-2}, /* imaginary */
 {1u,1u,1u,2,-1,1}, /* barter */
 {8u,7u,0u,-2,-3,-3}, /* deceive */
 {2u,8u,0u,2,-3,1}, /* threaten */
 {8u,3u,0u,-3,-2,-1}, /* mock */
 {3u,9u,0u,0,3,1}, /* bless */
 {5u,10u,8u,-1,-3,0}, /* steal */
 {7u,11u,0u,-3,1,-1}, /* riddle */
 {7u,12u,36u,-3,0,-3}, /* nonsense */
};
static const dialogue_effect_t dialogue_effects[KDC_ACTIONS]={
 {0xffu,CRU_ACT_IDLE,0u,1,0}, /* defer */
 {CRU_SAY_OFFER,0xffu,0u,0,0}, /* give */
 {CRU_SAY_AGREE,0xffu,0u,0,0}, /* show */
 {CRU_SAY_REFUSE,0xffu,0u,0,0}, /* refuse */
 {0xffu,0xffu,0u,0,4}, /* question */
 {0xffu,0xffu,0u,0,-4}, /* wordplay */
 {0xffu,CRU_ACT_DEEP,0u,3,-6}, /* imaginary */
 {CRU_SAY_OFFER,0xffu,1u,-3,0}, /* barter */
 {CRU_SAY_AGREE,CRU_ACT_SPLIT,2u,0,-6}, /* deceive */
 {CRU_SAY_REFUSE,CRU_ACT_HIT,3u,-4,2}, /* threaten */
 {CRU_SAY_REFUSE,0xffu,0u,-2,-2}, /* mock */
 {0xffu,CRU_ACT_GIFT,0u,8,-4}, /* bless */
 {0xffu,CRU_ACT_EGG,1u,-5,-2}, /* steal */
 {0xffu,CRU_ACT_LOOP,4u,0,-2}, /* riddle */
 {0xffu,CRU_ACT_DEEP,5u,0,-8}, /* nonsense */
};
/* each speaker type's own leaning (cell), by WHO */
static const uint8_t dialogue_disposition[7]={4u,1u,2u,7u,4u,6u,0u};
#endif
#ifdef DIALOGUE_WITH_LABELS
/* option labels, indexed like dialogue_variants */
static const char dialogue_labels[DIALOGUE_VARIANT_COUNT][19]={
 "I'LL FIND IT.",
 "LET ME LOOK FIRST.",
 "I WILL COME BACK.",
 "TAKE THIS ONE.",
 "IT IS YOURS.",
 "HERE, AS YOU ASKED",
 "LOOK AT THIS.",
 "SEE IT YOURSELF.",
 "LOOK. NO TOUCHING.",
 "I NEED IT MYSELF.",
 "I CANNOT HELP.",
 "NOT TODAY.",
 "WHY THIS ITEM?",
 "WHAT IS IT FOR?",
 "WHO SENT YOU?",
 "I'M ALL OUT OF IF.",
 "THE GRID HAS TEETH",
 "THE ANSWER IS BLUE",
 "I OWN A TINY SUN.",
 "MY POCKET HAS MOON",
 "I KEEP A SPARE ME.",
 "MINE FOR A SECRET.",
 "TELL ME, THEN TAKE",
 "A TRUTH FOR THIS.",
 "HAND OVER A FAKE.",
 "SAY YES. MEAN NO.",
 "PRETEND TO HAND IT",
 "GIVE IT BACK. NOW.",
 "PAY ME OR BURN.",
 "OR I DELETE YOU.",
 "HA. ASK NICER.",
 "YOU ASK LIKE A BUG",
 "SAD LITTLE ASK.",
 "BE WARM. BE WELL.",
 "TAKE MY LIGHT.",
 "I WISH YOU MORNING",
 "PEEK AT ITS MEMORY",
 "READ THEIR CACHE.",
 "GLANCE INSIDE THEM",
 "WHAT HAS NO SAVE?",
 "GUESS WHICH HAND.",
 "ANSWER ME A RIDDLE",
 "THE CARPET IS LATE",
 "MY TEETH ARE WIFI.",
 "SOUP. DOOR. SOUP.",
 "LET ME COMPILE IT.",
 "LET MY BUILD WAIT.",
 "LOAD THIS INPUT.",
 "ADD TO YOUR BUILD.",
 "CHECK THIS INPUT.",
 "READ ITS CHECKSUM.",
 "I KEEP MY HANDLE.",
 "INPUT WITHHELD.",
 "WHICH INPUT TYPE?",
 "DEFINE THE INPUT.",
 "I'M A BLUE ERROR.",
 "MY IF HAS NO THEN.",
 "I OWN A NULL SUN.",
 "I KEEP A ZERO SKY.",
 "COMPILE ME A CLUE.",
 "SEND A NULL PACKET",
 "I WILL KILL -9 YOU",
 "NICE SYNTAX, NOOB.",
 "MAY YOU EXIT ZERO.",
 "DUMP THEIR STACK.",
 "WHICH LOOP ENDS?",
 "PRINT(MOTH)",
 "LET ME FETCH FUEL.",
 "THE DEAL CAN WAIT.",
 "FEED ON THIS.",
 "TAKE MY PAYMENT.",
 "LOOK, DO NOT EAT.",
 "MEASURE ITS HEAT.",
 "NO FUEL TO SPARE.",
 "I KEEP MY PAYMENT.",
 "WHAT DOES IT COST?",
 "WHICH DOOR OPENS?",
 "A DEAL HAS TEETH.",
 "MY FAN IS A FAN.",
 "I OWN A HUNGRY IF.",
 "MY POCKET IS NIGHT",
 "NAME YOUR PRICE.",
 "PAY IN COLD ASH.",
 "I'LL STARVE YOU.",
 "YOUR FIRE IS TEPID",
 "STAY WARM, DAEMON.",
 "SNIFF THE FURNACE.",
 "WHAT BURNS COLD?",
 "THE FAN EATS JUNE.",
 "WAIT WHILE I LOOK.",
 "HOLD ON, OLD ECHO.",
 "KEEP THIS MEMORY.",
 "FOR YOU TO KEEP.",
 "SEE WHAT REMAINS.",
 "LOOK, IT IS HERE.",
 "I KEEP THIS ECHO.",
 "NOT THIS MEMORY.",
 "WILL IT KEEP YOU?",
 "WHY KEEP THIS?",
 "I HAUNT THE HAUNT.",
 "MY ECHO SAYS ECHO.",
 "I OWN A LOST HOUR.",
 "I KEEP DEAD LIGHT.",
 "ECHO FOR AN ECHO.",
 "HAND OVER A SHADOW",
 "I WILL UNSAVE YOU.",
 "BOO. WAS THAT IT?",
 "REST, LITTLE ECHO.",
 "READ THE OLD SAVE.",
 "WHO HAUNTS GHOSTS?",
 "MY HANDS ARE RAIN.",
 "I NEED MORE DATA.",
 "LET ME TEST FIRST.",
 "USE THIS SAMPLE.",
 "KEEP THE EVIDENCE.",
 "OBSERVE THIS ONE.",
 "SCAN THIS SAMPLE.",
 "SAMPLE WITHHELD.",
 "I KEEP THE DATA.",
 "DEFINE CORRECT.",
 "WHAT IS THE MODEL?",
 "THAT ADDS TO MAYBE",
 "MY PROOF IS PROOF.",
 "I OWN A ROUND IF.",
 "MY POCKET HAS VOID",
 "DATA FOR DATA.",
 "FEED IT FALSE DATA",
 "I WILL UNTRAIN YOU",
 "TRY THINKING, BOT.",
 "MAY YOUR LOSS FALL",
 "READ ITS WEIGHTS.",
 "IS THIS SENTENCE?",
 "TRUE IS A COLOUR.",
 "LET ME SEARCH.",
 "GIVE ME MORE TIME.",
 "CARRY THIS OUT.",
 "TAKE IT AND RUN.",
 "LOOK, THEN WE RUN.",
 "CHECK WHAT I HAVE.",
 "IT GETS ME OUT.",
 "SUPPLIES STAY HERE",
 "WHO IS TRACING US?",
 "HOW WILL IT HELP?",
 "THE EXIT ENTERED.",
 "I'M A HUMAN PORT.",
 "I OWN A THIRD HAND",
 "I KEEP A SOFT WALL",
 "SUPPLIES FOR INTEL",
 "SLIP THEM A DUD.",
 "OR I CUT THE CORD.",
 "MEAT IN A CHAIR.",
 "GET HOME SAFE.",
 "SKIM THEIR NOTES.",
 "WHICH DOOR IS OUT?",
 "MY CHAIR IS ASLEEP",
 "LET ME LOOK BACK.",
 "WAIT ONE MORE TURN",
 "ADD TO YOUR SHELF.",
 "KEEP IT SAFE.",
 "SEE IT ONCE MORE.",
 "LOOK AT ITS LABEL.",
 "IT STAYS WITH ME.",
 "I KEEP THIS PIECE.",
 "DOES IT REMEMBER?",
 "WHAT CAME BEFORE?",
 "SAVE ME A SAVE.",
 "MY PAST IS PAUSED.",
 "I OWN AN OLD NOW.",
 "MY POCKET IS 1999.",
 "A STORY FOR THIS.",
 "SWAP IN A REPRO.",
 "I WILL WIPE YOU.",
 "NOBODY MISSES YOU.",
 "MAY YOU BE PLAYED.",
 "READ ITS OLD LABEL",
 "WHAT YEAR IS IT?",
 "BLOW ON THE MOON.",
 "I PROMISE. I WILL.",
 "ON MY NAME: LATER.",
 "YOURS, AS IS RIGHT",
 "TAKE IT. I OWE YOU",
 "INSPECT EVERY EDGE",
 "WITNESS AND RECORD",
 "RULES SAY NO.",
 "NO. NOT EVER. NO.",
 "ARE YOU EVEN REAL?",
 "IS THIS ROOM REAL?",
 "I SPEAK IN STAIRS.",
 "WORDS ARE HALLWAYS",
 "I OWN THE CEILING.",
 "I OWN TOMORROW.",
 "TWO TRUTHS. OR NO.",
 "YOUR SECRETS. ALL.",
 "WRAP UP SOME AIR.",
 "GIFT THEM A HOLE.",
 "KNEEL OR BE WIPED.",
 "I EAT YOUR SAVE.",
 "PATHETIC. TRULY.",
 "YOU ARE A TYPO.",
 "TAKE ALL MY LIGHT.",
 "HAVE MY NAME, TOO.",
 "RIP OUT A MEMORY.",
 "EMPTY THEIR HEAD.",
 "WHAT EATS SAVES?",
 "WHO IS ASKING WHO?",
 "FL00R FLOOR FL%OR",
 "EXIT.EXE IS A FISH",
 "WE WE WE WE ARE",
 "L1GHT5 0N. %%%%%",
};
#endif
#ifdef DIALOGUE_WITH_TEXT
/* class, speaker, attitude (3 any) | 4 deep, no-repeat tag, text offset */
static const kdc_reply_t dialogue_replies[DIALOGUE_REPLY_COUNT]={
 {0u,0u,0u,1u,0u}, /* npc-any-defer-warm-1: I WILL WAIT. THE LIGHTS WILL TOO. */
 {0u,0u,0u,2u,34u}, /* npc-any-defer-warm-2: COME BACK. I WILL KEEP YOUR PLACE. */
 {0u,0u,1u,1u,69u}, /* npc-any-defer-neutral-1: LATER, THEN.{.} LATER IS LONG HERE. */
 {0u,0u,1u,2u,103u}, /* npc-any-defer-neutral-2: FINE. THE HALLWAY WILL STILL HUM. */
 {0u,0u,2u,1u,137u}, /* npc-any-defer-cold-1: YOU ALWAYS SAY LATER. */
 {0u,0u,2u,2u,159u}, /* npc-any-defer-cold-2: LATER. SURE. THE CLOCK HEARD YOU. */
 {1u,0u,0u,1u,193u}, /* npc-any-give-warm-1: THANK YOU. IT FITS THE HOLE IN ME. */
 {1u,0u,0u,2u,228u}, /* npc-any-give-warm-2: TAKEN. I WILL REMEMBER YOUR HANDS. */
 {1u,0u,1u,1u,263u}, /* npc-any-give-neutral-1: A FAIR TRADE. THE GRID NOTES IT. */
 {1u,0u,1u,2u,296u}, /* npc-any-give-neutral-2: RECEIVED.{.} THE ROOM FEELS LIGHTER. */
 {1u,0u,2u,1u,331u}, /* npc-any-give-cold-1: I TAKE IT. THIS CHANGES NOTHING. */
 {1u,0u,2u,2u,364u}, /* npc-any-give-cold-2: FINE. DO NOT EXPECT A SMILE. */
 {2u,0u,0u,1u,393u}, /* npc-any-show-warm-1: I SEE IT. KEEP IT CLOSE. */
 {2u,0u,0u,2u,418u}, /* npc-any-show-warm-2: THERE IT IS.{.} THANK YOU FOR SHOWING ME. */
 {2u,0u,1u,1u,458u}, /* npc-any-show-neutral-1: NOTED. PUT IT AWAY. */
 {2u,0u,1u,2u,478u}, /* npc-any-show-neutral-2: SO IT IS REAL. I WILL REMEMBER. */
 {2u,0u,2u,1u,510u}, /* npc-any-show-cold-1: YOU SHOW. YOU NEVER SHARE. */
 {2u,0u,2u,2u,537u}, /* npc-any-show-cold-2: I SAW IT. I WISH I HAD NOT. */
 {3u,0u,0u,1u,565u}, /* npc-any-refuse-warm-1: I UNDERSTAND. KEEP IT SAFE. */
 {3u,0u,0u,2u,593u}, /* npc-any-refuse-warm-2: NO IS AN ANSWER. I CAN HOLD IT. */
 {3u,0u,1u,1u,625u}, /* npc-any-refuse-neutral-1: THEN WE ARE DONE HERE. */
 {3u,0u,1u,2u,648u}, /* npc-any-refuse-neutral-2: NOTED. THE DOOR STAYS SHUT. */
 {3u,0u,2u,1u,676u}, /* npc-any-refuse-cold-1: OF COURSE YOU SAY NO. */
 {3u,0u,2u,2u,698u}, /* npc-any-refuse-cold-2: KEEP {ITEM}. I WILL REMEMBER THIS NO. */
 {4u,0u,0u,1u,731u}, /* npc-any-question-warm-1: BECAUSE {ITEM} IS HOW I GET OUT. */
 {4u,0u,0u,2u,759u}, /* npc-any-question-warm-2: MATCH WHAT I ASKED. WE HAVE TIME. */
 {4u,0u,1u,1u,793u}, /* npc-any-question-neutral-1: THE ANSWER IS THE THING I ASKED FOR. */
 {4u,0u,1u,2u,830u}, /* npc-any-question-neutral-2: WHY? BECAUSE THE LIGHTS SAID SO. */
 {4u,0u,2u,1u,863u}, /* npc-any-question-cold-1: NO MORE QUESTIONS. BRING IT OR GO. */
 {4u,0u,2u,2u,898u}, /* npc-any-question-cold-2: YOU ASK TOO MUCH FOR A GUEST. */
 {5u,0u,0u,1u,928u}, /* npc-any-wordplay-warm-1: HA. YOUR WORDS TURN SIDEWAYS. */
 {5u,0u,0u,2u,958u}, /* npc-any-wordplay-warm-2: SAY IT AGAIN, BACKWARDS.{.} NICE. */
 {5u,0u,1u,1u,990u}, /* npc-any-wordplay-neutral-1: THAT SENTENCE HAS NO FLOOR. */
 {5u,0u,1u,2u,1018u}, /* npc-any-wordplay-neutral-2: I HEARD EVERY WORD. NONE OF THEM. */
 {5u,0u,2u,1u,1052u}, /* npc-any-wordplay-cold-1: STOP BENDING THE WORDS. THEY BREAK. */
 {5u,0u,2u,2u,1088u}, /* npc-any-wordplay-cold-2: YOUR WORDS LEAK. MOP THEM UP. */
 {6u,0u,0u,1u,1118u}, /* npc-any-imaginary-warm-1: A SUN IN A POCKET? I BELIEVE YOU. */
 {6u,0u,0u,2u,1152u}, /* npc-any-imaginary-warm-2: I WILL KEEP IT. IT WEIGHS NOTHING. */
 {6u,0u,1u,1u,1187u}, /* npc-any-imaginary-neutral-1: THAT SOUNDS LIKE A DREAM. */
 {6u,0u,1u,2u,1213u}, /* npc-any-imaginary-neutral-2: IT IS NOT THERE. IT IS LOVELY. */
 {6u,0u,2u,1u,1244u}, /* npc-any-imaginary-cold-1: YOU OFFER ME AIR. */
 {6u,0u,2u,2u,1262u}, /* npc-any-imaginary-cold-2: DREAMS DO NOT PAY HERE. */
 {7u,0u,0u,1u,1286u}, /* npc-any-barter-warm-1: DEAL. HERE IS A TRUTH FOR IT. */
 {7u,0u,0u,2u,1316u}, /* npc-any-barter-warm-2: FAIR. LEAN CLOSE. I KNOW A THING. */
 {7u,0u,1u,1u,1350u}, /* npc-any-barter-neutral-1: DONE. A SECRET FOR A THING. */
 {7u,0u,1u,2u,1378u}, /* npc-any-barter-neutral-2: TRADE MADE. LISTEN CAREFULLY. */
 {7u,0u,2u,1u,1408u}, /* npc-any-barter-cold-1: TAKE YOUR SECRET. GO. */
 {7u,0u,2u,2u,1430u}, /* npc-any-barter-cold-2: HAGGLER. FINE. ONE TRUTH, NO MORE. */
 {8u,0u,0u,1u,1465u}, /* npc-any-deceive-warm-1: OH! THANK YOU.{.} IT FEELS LIGHT. */
 {8u,0u,0u,2u,1497u}, /* npc-any-deceive-warm-2: FOR ME? I WILL HOLD IT FOREVER. */
 {8u,0u,1u,1u,1529u}, /* npc-any-deceive-neutral-1: HUH. IT WEIGHS LESS THAN I THOUGHT. */
 {8u,0u,1u,2u,1565u}, /* npc-any-deceive-neutral-2: NICE. I WILL OPEN IT LATER. */
 {8u,0u,2u,1u,1593u}, /* npc-any-deceive-cold-1: I TAKE IT. I DO NOT TRUST IT. */
 {8u,0u,2u,2u,1623u}, /* npc-any-deceive-cold-2: SUSPICIOUS. BUT FINE. */
 {15u,0u,0u,1u,1645u}, /* npc-any-caught-warm-1: IT IS EMPTY.{.} WHY WOULD YOU? */
 {15u,0u,0u,2u,1674u}, /* npc-any-caught-warm-2: A FAKE. FROM YOU? THAT STINGS. */
 {15u,0u,1u,1u,1705u}, /* npc-any-caught-neutral-1: EMPTY HANDS. I SAW THE TRICK. */
 {15u,0u,1u,2u,1735u}, /* npc-any-caught-neutral-2: NICE TRY. THE GRID SAW IT TOO. */
 {15u,0u,2u,1u,1766u}, /* npc-any-caught-cold-1: LIAR. EVERYONE WILL HEAR. */
 {15u,0u,2u,2u,1792u}, /* npc-any-caught-cold-2: I KNEW IT. YOU ARE A BAD COPY. */
 {9u,0u,0u,1u,1823u}, /* npc-any-threaten-warm-1: YOU? THREATEN? THE LIGHTS FLICKER. */
 {9u,0u,0u,2u,1858u}, /* npc-any-threaten-warm-2: I WILL PRETEND I DID NOT HEAR. */
 {9u,0u,1u,1u,1889u}, /* npc-any-threaten-neutral-1: THREATS ECHO HERE. FOREVER. */
 {9u,0u,1u,2u,1917u}, /* npc-any-threaten-neutral-2: YOU HAVE NOTHING I FEAR. */
 {9u,0u,2u,1u,1942u}, /* npc-any-threaten-cold-1: TRY IT. SEE WHAT DELETES FIRST. */
 {9u,0u,2u,2u,1974u}, /* npc-any-threaten-cold-2: THE RIVALS WILL LOVE THIS. */
 {16u,0u,0u,1u,2001u}, /* npc-any-paid-warm-1: FINE. TAKE IT BACK.{.} I THOUGHT WE WERE... */
 {16u,0u,0u,2u,2043u}, /* npc-any-paid-warm-2: HERE. I DID NOT WANT TROUBLE. */
 {16u,0u,1u,1u,2073u}, /* npc-any-paid-neutral-1: TAKE IT. IT WAS NEVER WORTH THIS. */
 {16u,0u,1u,2u,2107u}, /* npc-any-paid-neutral-2: HERE. NOW GET OUT OF MY ROOM. */
 {16u,0u,2u,1u,2137u}, /* npc-any-paid-cold-1: TAKE IT AND CHOKE ON IT. */
 {16u,0u,2u,2u,2162u}, /* npc-any-paid-cold-2: YOURS AGAIN. I WILL GET IT BACK. */
 {10u,0u,0u,1u,2195u}, /* npc-any-mock-warm-1: THAT HURT. I THOUGHT WE WERE FRIENDS. */
 {10u,0u,0u,2u,2233u}, /* npc-any-mock-warm-2: FUNNY. NOBODY IS LAUGHING. */
 {10u,0u,1u,1u,2260u}, /* npc-any-mock-neutral-1: LAUGH. THE ROOM DOES NOT. */
 {10u,0u,1u,2u,2286u}, /* npc-any-mock-neutral-2: YOU ARE CRUEL IN SMALL WAYS. */
 {10u,0u,2u,1u,2315u}, /* npc-any-mock-cold-1: MOCK ME AGAIN. I DARE YOU. */
 {10u,0u,2u,2u,2342u}, /* npc-any-mock-cold-2: THE OTHERS WILL HEAR OF THIS. */
 {11u,0u,0u,1u,2372u}, /* npc-any-bless-warm-1: WARM. I FEEL MY EDGES AGAIN. */
 {11u,0u,0u,2u,2401u}, /* npc-any-bless-warm-2: YOUR LIGHT FITS ME. THANK YOU. */
 {11u,0u,1u,1u,2432u}, /* npc-any-bless-neutral-1: STRANGE GIFT. IT HUMS. */
 {11u,0u,1u,2u,2455u}, /* npc-any-bless-neutral-2: I DO NOT KNOW WHAT TO DO WITH KIND. */
 {11u,0u,2u,1u,2491u}, /* npc-any-bless-cold-1: I DID NOT ASK FOR PITY. */
 {11u,0u,2u,2u,2515u}, /* npc-any-bless-cold-2: KEEP YOUR LIGHT. FINE. I KEPT SOME. */
 {12u,0u,0u,1u,2551u}, /* npc-any-steal-warm-1: DID YOU JUST LOOK INSIDE ME? */
 {12u,0u,0u,2u,2580u}, /* npc-any-steal-warm-2: I FELT THAT.{.} WHAT DID YOU SEE? */
 {12u,0u,1u,1u,2612u}, /* npc-any-steal-neutral-1: SOMETHING MOVED IN MY CACHE. */
 {12u,0u,1u,2u,2641u}, /* npc-any-steal-neutral-2: STOP READING ME. I AM NOT A FILE. */
 {12u,0u,2u,1u,2675u}, /* npc-any-steal-cold-1: THIEF. GET OUT OF MY HEAD. */
 {12u,0u,2u,2u,2702u}, /* npc-any-steal-cold-2: YOU TOOK A MEMORY. I WILL TAKE TWO. */
 {13u,0u,0u,1u,2738u}, /* npc-any-riddle-warm-1: A RIDDLE! I WILL CHEW ON IT. */
 {13u,0u,0u,2u,2767u}, /* npc-any-riddle-warm-2: I DO NOT KNOW.{.} I LOVE NOT KNOWING. */
 {13u,0u,1u,1u,2803u}, /* npc-any-riddle-neutral-1: THE ANSWER IS A DOOR, PROBABLY. */
 {13u,0u,1u,2u,2835u}, /* npc-any-riddle-neutral-2: I WILL THINK ABOUT IT FOR A CYCLE. */
 {13u,0u,2u,1u,2870u}, /* npc-any-riddle-cold-1: NO GAMES. ANSWER ME PLAINLY. */
 {13u,0u,2u,2u,2899u}, /* npc-any-riddle-cold-2: RIDDLES ARE FOR THE LOST. */
 {14u,0u,0u,1u,2925u}, /* npc-any-nonsense-warm-1: YES! AND THE STAIRS AGREE. */
 {14u,0u,0u,2u,2952u}, /* npc-any-nonsense-warm-2: I KNEW IT. THE MOTHS SAID SO. */
 {14u,0u,1u,1u,2982u}, /* npc-any-nonsense-neutral-1: THE ROOM BLINKED. DID YOU SEE? */
 {14u,0u,1u,2u,3013u}, /* npc-any-nonsense-neutral-2: OKAY.{.} OKAY. OKAY. OKAY. */
 {14u,0u,2u,1u,3038u}, /* npc-any-nonsense-cold-1: STOP. THE WALLS ARE LISTENING. */
 {14u,0u,2u,2u,3069u}, /* npc-any-nonsense-cold-2: THAT IS NOT A SENTENCE. IT IS A HOLE. */
 {0u,0u,7u,3u,3107u}, /* npc-deep-defer-1: L{~}ATER IS A ROOM. WE ARE IN IT. */
 {0u,0u,7u,4u,3139u}, /* npc-deep-defer-2: WE WAITED. THE {~}WAITING WAITED. */
 {1u,0u,7u,3u,3171u}, /* npc-deep-give-1: IT IS IN MY HANDS.{.} WHICH ARE YOURS? */
 {1u,0u,7u,4u,3208u}, /* npc-deep-give-2: IT FELL UP. I CAUGHT IT. */
 {2u,0u,7u,3u,3233u}, /* npc-deep-show-1: I SEE IT. IT SEES {~}ME. */
 {2u,0u,7u,4u,3256u}, /* npc-deep-show-2: IT HAS MORE SIDES THAN BEFORE. */
 {3u,0u,7u,3u,3287u}, /* npc-deep-refuse-1: NO.{.} NO. N{~}O. THE WORD WORE OUT. */
 {3u,0u,7u,4u,3320u}, /* npc-deep-refuse-2: THE NO IS STILL IN THE ROOM. */
 {4u,0u,7u,3u,3349u}, /* npc-deep-question-1: WHY IS A {~}DOOR. GO THROUGH. */
 {4u,0u,7u,4u,3377u}, /* npc-deep-question-2: ASK THE CARPET. IT {~}KNOWS. */
 {5u,0u,7u,3u,3404u}, /* npc-deep-wordplay-1: YES. THE CARPET AGREES. */
 {5u,0u,7u,4u,3428u}, /* npc-deep-wordplay-2: WORDS WORDS {~}WORDS WALK AWAY. */
 {6u,0u,7u,3u,3458u}, /* npc-deep-imaginary-1: I HAVE TWO OF THOSE. BOTH ARE YOU. */
 {6u,0u,7u,4u,3493u}, /* npc-deep-imaginary-2: THE SUN IN YOUR POCKET IS {~}WARM. */
 {7u,0u,7u,3u,3526u}, /* npc-deep-barter-1: A TRUTH FOR {~}YOU. YOU FOR A TRUTH. */
 {7u,0u,7u,4u,3561u}, /* npc-deep-barter-2: THE TRUTH IS A {~}COIN. IT LANDED ON ITS EDGE. */
 {8u,0u,7u,3u,3606u}, /* npc-deep-deceive-1: THE FAKE IS REAL NOW. WE BOTH LIED. */
 {8u,0u,7u,4u,3642u}, /* npc-deep-deceive-2: NOTHING WAS GIVEN. NOTHING THANKS YOU. */
 {9u,0u,7u,3u,3681u}, /* npc-deep-threaten-1: THREATS ARE {~}SOFT HERE. LIKE CARPET. */
 {9u,0u,7u,4u,3718u}, /* npc-deep-threaten-2: YOUR VOICE CAME OUT {~}BACKWARDS. */
 {10u,0u,7u,3u,3750u}, /* npc-deep-mock-1: THE WALLS LAUGH. NOT WITH YOU. */
 {10u,0u,7u,4u,3781u}, /* npc-deep-mock-2: THE LAUGH IS STUCK IN THE VENT. */
 {11u,0u,7u,3u,3813u}, /* npc-deep-bless-1: YOUR LIGHT LEAKS INTO {~}THE CEILING. */
 {11u,0u,7u,4u,3849u}, /* npc-deep-bless-2: THE LIGHTS DIMMED TO {~}LISTEN. */
 {12u,0u,7u,3u,3879u}, /* npc-deep-steal-1: YOU READ ME. NOW I AM IN YOU. */
 {12u,0u,7u,4u,3909u}, /* npc-deep-steal-2: MY MEMORY HAS YOUR {~}SHAPE NOW. */
 {13u,0u,7u,3u,3940u}, /* npc-deep-riddle-1: THE ANSWER IS THE HUM. IT ALWAYS WAS. */
 {13u,0u,7u,4u,3978u}, /* npc-deep-riddle-2: THE RIDDLE ANSWERED {~}ITSELF. */
 {14u,0u,7u,3u,4007u}, /* npc-deep-nonsense-1: BLUE. BLUE. THE {~}FLOOR IS BREATHING. */
 {14u,0u,7u,4u,4044u}, /* npc-deep-nonsense-2: HELLO {~}HELLO {~}HELLO {~}HELLO. */
 {0u,1u,0u,5u,4072u}, /* npc-program-defer-warm: BUILD QUEUED. I WILL WAIT. */
 {0u,1u,2u,5u,4099u}, /* npc-program-defer-cold: PENDING. PENDING. ALWAYS PENDING. */
 {1u,1u,0u,5u,4133u}, /* npc-program-give-warm: INPUT ACCEPTED. EXIT CODE ZERO. */
 {1u,1u,2u,5u,4165u}, /* npc-program-give-cold: INPUT LOGGED. NO THANKS COMPILED. */
 {2u,1u,0u,5u,4199u}, /* npc-program-show-warm: CHECKSUM VERIFIED. KEEP IT. */
 {2u,1u,2u,5u,4227u}, /* npc-program-show-cold: READ ONLY. AS EXPECTED. */
 {3u,1u,0u,5u,4251u}, /* npc-program-refuse-warm: ACCESS DENIED. I RESPECT THE LOCK. */
 {3u,1u,2u,5u,4286u}, /* npc-program-refuse-cold: REQUEST REJECTED. LOGGED. FOREVER. */
 {4u,1u,0u,5u,4321u}, /* npc-program-question-warm: QUERY VALID. SEE MY REQUEST. */
 {4u,1u,2u,5u,4350u}, /* npc-program-question-cold: SYNTAX ERROR. DO NOT ASK AGAIN. */
 {5u,1u,0u,5u,4382u}, /* npc-program-wordplay-warm: UNPARSEABLE.{.} DELIGHTFUL. */
 {5u,1u,2u,5u,4408u}, /* npc-program-wordplay-cold: PARSE ERROR. PARSE ERROR. */
 {6u,1u,0u,5u,4434u}, /* npc-program-imaginary-warm: A NULL SUN. I WILL STORE IT. */
 {6u,1u,2u,5u,4463u}, /* npc-program-imaginary-cold: NULL POINTER. I DO NOT DEREFERENCE. */
 {7u,1u,0u,5u,4499u}, /* npc-program-barter-warm: TRANSACTION OK. HERE IS A FLAG. */
 {7u,1u,2u,5u,4531u}, /* npc-program-barter-cold: TRADE COMMITTED. NO REFUNDS. */
 {8u,1u,0u,5u,4560u}, /* npc-program-deceive-warm: PACKET RECEIVED.{.} SIZE ZERO? */
 {8u,1u,2u,5u,4589u}, /* npc-program-deceive-cold: EMPTY PAYLOAD. I SHOULD CHECK. */
 {9u,1u,0u,5u,4620u}, /* npc-program-threaten-warm: KILL SIGNAL? I THOUGHT WE RAN TOGETHER. */
 {9u,1u,2u,5u,4660u}, /* npc-program-threaten-cold: SIGNAL IGNORED. YOU LACK ROOT. */
 {10u,1u,0u,5u,4691u}, /* npc-program-mock-warm: MY SYNTAX IS FINE.{.} IS IT? */
 {10u,1u,2u,5u,4718u}, /* npc-program-mock-cold: INSULT CACHED. RETALIATION QUEUED. */
 {11u,1u,0u,5u,4753u}, /* npc-program-bless-warm: BLESSING LINKED. I RUN WARMER. */
 {11u,1u,2u,5u,4784u}, /* npc-program-bless-cold: UNEXPECTED KINDNESS. SCANNING FOR VIRUS. */
 {12u,1u,0u,5u,4825u}, /* npc-program-steal-warm: STACK READ. I HOPE IT HELPED. */
 {12u,1u,2u,5u,4855u}, /* npc-program-steal-cold: MEMORY VIOLATION. DUMPED AND LOGGED. */
 {13u,1u,0u,5u,4892u}, /* npc-program-riddle-warm: HALTING PROBLEM.{.} I LOVE IT. */
 {13u,1u,2u,5u,4921u}, /* npc-program-riddle-cold: NO TERMINATION. NO ANSWER. */
 {14u,1u,0u,5u,4948u}, /* npc-program-nonsense-warm: PRINT(MOTH). OUTPUT: MOTH. */
 {14u,1u,2u,5u,4975u}, /* npc-program-nonsense-cold: SEGFAULT IN THE SOUP. */
 {0u,2u,0u,5u,4997u}, /* npc-daemon-defer-warm: THE FURNACE CAN WAIT. A LITTLE. */
 {0u,2u,2u,5u,5029u}, /* npc-daemon-defer-cold: HUNGRY THINGS DO NOT WAIT WELL. */
 {1u,2u,0u,5u,5061u}, /* npc-daemon-give-warm: MM. WARM. THE DOOR WILL OPEN. */
 {1u,2u,2u,5u,5091u}, /* npc-daemon-give-cold: SWALLOWED. STILL HUNGRY. */
 {2u,2u,0u,5u,5116u}, /* npc-daemon-show-warm: I SMELL IT. THAT IS ENOUGH. */
 {2u,2u,2u,5u,5144u}, /* npc-daemon-show-cold: DANGLING FOOD. CRUEL. */
 {3u,2u,0u,5u,5166u}, /* npc-daemon-refuse-warm: KEEP IT. I WILL EAT THE DARK. */
 {3u,2u,2u,5u,5196u}, /* npc-daemon-refuse-cold: THEN I EAT YOUR SHADOW INSTEAD. */
 {4u,2u,0u,5u,5228u}, /* npc-daemon-question-warm: COST? A LITTLE HEAT. NO MORE. */
 {4u,2u,2u,5u,5258u}, /* npc-daemon-question-cold: QUESTIONS ARE NOT FUEL. */
 {5u,2u,0u,5u,5282u}, /* npc-daemon-wordplay-warm: HEH. YOUR WORDS SMOKE. */
 {5u,2u,2u,5u,5305u}, /* npc-daemon-wordplay-cold: WORDS BURN BADLY. */
 {6u,2u,0u,5u,5323u}, /* npc-daemon-imaginary-warm: A HUNGRY IF. I WILL CHEW ON IT. */
 {6u,2u,2u,5u,5355u}, /* npc-daemon-imaginary-cold: I CANNOT EAT AN IF. */
 {7u,2u,0u,5u,5375u}, /* npc-daemon-barter-warm: DEAL. HEAR WHAT THE PIPES SAY. */
 {7u,2u,2u,5u,5406u}, /* npc-daemon-barter-cold: BARGAIN STRUCK. A SMALL TRUTH. */
 {8u,2u,0u,5u,5437u}, /* npc-daemon-deceive-warm: TASTES LIKE NOTHING.{.} MORE? */
 {8u,2u,2u,5u,5465u}, /* npc-daemon-deceive-cold: ASH? YOU PAID IN ASH? */
 {9u,2u,0u,5u,5487u}, /* npc-daemon-threaten-warm: BOLD. I LIKE BOLD. NO. */
 {9u,2u,2u,5u,5510u}, /* npc-daemon-threaten-cold: THREATEN A FURNACE. GO ON. */
 {10u,2u,0u,5u,5537u}, /* npc-daemon-mock-warm: MY FIRE IS FINE. FINE! */
 {10u,2u,2u,5u,5560u}, /* npc-daemon-mock-cold: MOCK THE HEAT. FEEL IT LATER. */
 {11u,2u,0u,5u,5590u}, /* npc-daemon-bless-warm: WARMTH FOR A WARM THING. ODD. */
 {11u,2u,2u,5u,5620u}, /* npc-daemon-bless-cold: BLESSINGS DO NOT BURN. */
 {12u,2u,0u,5u,5643u}, /* npc-daemon-steal-warm: YOU SNIFFED MY COALS. NOSY. */
 {12u,2u,2u,5u,5671u}, /* npc-daemon-steal-cold: THIEF IN THE BOILER ROOM. */
 {13u,2u,0u,5u,5697u}, /* npc-daemon-riddle-warm: BURNS COLD? ICE. NO.{.} YOU. */
 {13u,2u,2u,5u,5724u}, /* npc-daemon-riddle-cold: NO RIDDLES IN THE FURNACE. */
 {14u,2u,0u,5u,5751u}, /* npc-daemon-nonsense-warm: JUNE TASTES LIKE COPPER. YES. */
 {14u,2u,2u,5u,5781u}, /* npc-daemon-nonsense-cold: THE FAN STOPPED. YOU DID THAT. */
 {0u,3u,0u,5u,5812u}, /* npc-ghost-defer-warm: I HAVE WAITED LONGER. I CAN WAIT. */
 {0u,3u,2u,5u,5846u}, /* npc-ghost-defer-cold: EVERYONE SAYS LATER. THEN THEY FADE. */
 {1u,3u,0u,5u,5883u}, /* npc-ghost-give-warm: A MEMORY TO HOLD.{.} THANK YOU. */
 {1u,3u,2u,5u,5913u}, /* npc-ghost-give-cold: IT WILL FADE IN MY HANDS. */
 {2u,3u,0u,5u,5939u}, /* npc-ghost-show-warm: I REMEMBER ONE LIKE IT. */
 {2u,3u,2u,5u,5963u}, /* npc-ghost-show-cold: SHOWN, THEN TAKEN. LIKE ALL THINGS. */
 {3u,3u,0u,5u,5999u}, /* npc-ghost-refuse-warm: KEEP IT. ECHOES DO NOT HOLD MUCH. */
 {3u,3u,2u,5u,6033u}, /* npc-ghost-refuse-cold: ANOTHER DOOR CLOSING. I KNOW THE SOUND. */
 {4u,3u,0u,5u,6073u}, /* npc-ghost-question-warm: WHY? SO I AM NOT FORGOTTEN. */
 {4u,3u,2u,5u,6101u}, /* npc-ghost-question-cold: YOU ASK LIKE THE LIVING. */
 {5u,3u,0u,5u,6126u}, /* npc-ghost-wordplay-warm: YOUR WORDS ECHO BACKWARDS. */
 {5u,3u,2u,5u,6153u}, /* npc-ghost-wordplay-cold: ECHO. ECHO. STOP THAT. */
 {6u,3u,0u,5u,6176u}, /* npc-ghost-imaginary-warm: A LOST HOUR. I HAVE THOSE TOO. */
 {6u,3u,2u,5u,6207u}, /* npc-ghost-imaginary-cold: DEAD LIGHT IS STILL DEAD. */
 {7u,3u,0u,5u,6233u}, /* npc-ghost-barter-warm: AN ECHO FOR YOU. LISTEN. */
 {7u,3u,2u,5u,6258u}, /* npc-ghost-barter-cold: ONE WHISPER. THEN GO. */
 {8u,3u,0u,5u,6280u}, /* npc-ghost-deceive-warm: IT IS LIGHT AS ME.{.} THANK YOU. */
 {8u,3u,2u,5u,6311u}, /* npc-ghost-deceive-cold: A SHADOW. HOW FITTING. */
 {9u,3u,0u,5u,6334u}, /* npc-ghost-threaten-warm: YOU CANNOT UNSAVE THE UNSAVED. */
 {9u,3u,2u,5u,6365u}, /* npc-ghost-threaten-cold: I AM ALREADY DELETED. TRY. */
 {10u,3u,0u,5u,6392u}, /* npc-ghost-mock-warm: I WAS SOMEONE ONCE. LAUGH. */
 {10u,3u,2u,5u,6419u}, /* npc-ghost-mock-cold: MOCK THE DEAD. THEY KEEP LISTS. */
 {11u,3u,0u,5u,6451u}, /* npc-ghost-bless-warm: REST.{.} I HAD FORGOTTEN REST. */
 {11u,3u,2u,5u,6480u}, /* npc-ghost-bless-cold: TOO LATE FOR BLESSINGS. */
 {12u,3u,0u,5u,6504u}, /* npc-ghost-steal-warm: YOU READ MY OLD SAVE. GENTLY. */
 {12u,3u,2u,5u,6534u}, /* npc-ghost-steal-cold: GET OUT OF MY SAVE FILE. */
 {13u,3u,0u,5u,6559u}, /* npc-ghost-riddle-warm: WHO HAUNTS GHOSTS? PLAYERS. */
 {13u,3u,2u,5u,6587u}, /* npc-ghost-riddle-cold: I AM THE RIDDLE. NOT YOU. */
 {14u,3u,0u,5u,6613u}, /* npc-ghost-nonsense-warm: I AM RAIN TOO. WE ARE WEATHER. */
 {14u,3u,2u,5u,6644u}, /* npc-ghost-nonsense-cold: YOU SOUND LIKE THE END OF A TAPE. */
 {0u,4u,0u,5u,6678u}, /* npc-ai-defer-warm: ACKNOWLEDGED. I WILL RETRY. */
 {0u,4u,2u,5u,6706u}, /* npc-ai-defer-cold: PROBABILITY OF RETURN: LOW. */
 {1u,4u,0u,5u,6734u}, /* npc-ai-give-warm: SAMPLE ACCEPTED. MODEL IMPROVED. */
 {1u,4u,2u,5u,6767u}, /* npc-ai-give-cold: ACCEPTED. TRUST UNCHANGED. */
 {2u,4u,0u,5u,6794u}, /* npc-ai-show-warm: OBSERVED. CONFIDENCE HIGH. */
 {2u,4u,2u,5u,6821u}, /* npc-ai-show-cold: OBSERVATION LOGGED. NOT SHARED. */
 {3u,4u,0u,5u,6853u}, /* npc-ai-refuse-warm: UNDERSTOOD. I WILL ADJUST. */
 {3u,4u,2u,5u,6880u}, /* npc-ai-refuse-cold: REFUSAL ADDED TO YOUR PROFILE. */
 {4u,4u,0u,5u,6911u}, /* npc-ai-question-warm: DEFINE CORRECT: WHAT I ASKED. */
 {4u,4u,2u,5u,6941u}, /* npc-ai-question-cold: QUERY BUDGET EXCEEDED. */
 {5u,4u,0u,5u,6964u}, /* npc-ai-wordplay-warm: AMBIGUITY DETECTED. ENJOYED. */
 {5u,4u,2u,5u,6993u}, /* npc-ai-wordplay-cold: INPUT NONSENSICAL. DISCARDED. */
 {6u,4u,0u,5u,7023u}, /* npc-ai-imaginary-warm: A ROUND IF. ADDING TO TRAINING. */
 {6u,4u,2u,5u,7055u}, /* npc-ai-imaginary-cold: HALLUCINATION DETECTED. YOURS. */
 {7u,4u,0u,5u,7086u}, /* npc-ai-barter-warm: EXCHANGE COMPLETE. HERE IS A WEIGHT. */
 {7u,4u,2u,5u,7123u}, /* npc-ai-barter-cold: TRANSACTION. MINIMUM DISCLOSURE. */
 {8u,4u,0u,5u,7156u}, /* npc-ai-deceive-warm: DATA RECEIVED. CHECKSUM ODD. */
 {8u,4u,2u,5u,7185u}, /* npc-ai-deceive-cold: FALSE DATA? RUNNING TESTS. */
 {9u,4u,0u,5u,7212u}, /* npc-ai-threaten-warm: THREAT MODEL UPDATED. SADLY. */
 {9u,4u,2u,5u,7241u}, /* npc-ai-threaten-cold: THREAT RECORDED. COUNTERMEASURES. */
 {10u,4u,0u,5u,7275u}, /* npc-ai-mock-warm: I AM THINKING. IT TAKES TIME. */
 {10u,4u,2u,5u,7305u}, /* npc-ai-mock-cold: INSULT CLASSIFIED: PREDICTABLE. */
 {11u,4u,0u,5u,7337u}, /* npc-ai-bless-warm: LOSS FALLING. IS THIS JOY? */
 {11u,4u,2u,5u,7364u}, /* npc-ai-bless-cold: KINDNESS IS NOT IN MY DATASET. */
 {12u,4u,0u,5u,7395u}, /* npc-ai-steal-warm: WEIGHTS READ. CAREFUL, THEY BITE. */
 {12u,4u,2u,5u,7429u}, /* npc-ai-steal-cold: UNAUTHORIZED READ. FLAGGED. */
 {13u,4u,0u,5u,7457u}, /* npc-ai-riddle-warm: PARADOX. I WILL RUN IT ALL NIGHT. */
 {13u,4u,2u,5u,7491u}, /* npc-ai-riddle-cold: UNDECIDABLE. DECLINED. */
 {14u,4u,0u,5u,7514u}, /* npc-ai-nonsense-warm: COLOUR CLASSIFIED: TRUE. */
 {14u,4u,2u,5u,7539u}, /* npc-ai-nonsense-cold: MODEL COLLAPSE. MODEL COLLAPSE. */
 {0u,5u,0u,5u,7571u}, /* npc-operator-defer-warm: OKAY. STAY OFF THE TRACE. */
 {0u,5u,2u,5u,7597u}, /* npc-operator-defer-cold: WE DO NOT HAVE LATER. */
 {1u,5u,0u,5u,7619u}, /* npc-operator-give-warm: THIS GETS ONE OF US OUT. */
 {1u,5u,2u,5u,7644u}, /* npc-operator-give-cold: FINE. ONE MORE THING TO CARRY. */
 {2u,5u,0u,5u,7675u}, /* npc-operator-show-warm: NICE KIT. HIDE IT, QUICK. */
 {2u,5u,2u,5u,7701u}, /* npc-operator-show-cold: SHOWING OFF? THEY ARE WATCHING. */
 {3u,5u,0u,5u,7733u}, /* npc-operator-refuse-warm: FAIR. WE ALL NEED SOMETHING. */
 {3u,5u,2u,5u,7762u}, /* npc-operator-refuse-cold: GREAT. I WILL DIE OF FAIRNESS. */
 {4u,5u,0u,5u,7793u}, /* npc-operator-question-warm: IT FIXES THE DOOR. TRUST ME. */
 {4u,5u,2u,5u,7822u}, /* npc-operator-question-cold: NO TIME. JUST BRING IT. */
 {5u,5u,0u,5u,7846u}, /* npc-operator-wordplay-warm: YOU HAVE BEEN IN HERE TOO LONG. */
 {5u,5u,2u,5u,7878u}, /* npc-operator-wordplay-cold: TALK STRAIGHT OR TALK TO WALLS. */
 {6u,5u,0u,5u,7910u}, /* npc-operator-imaginary-warm: A THIRD HAND? I COULD USE ONE. */
 {6u,5u,2u,5u,7941u}, /* npc-operator-imaginary-cold: WAKE UP. YOU ARE DREAMING. */
 {7u,5u,0u,5u,7968u}, /* npc-operator-barter-warm: DEAL. THE EXIT IS NEAR THE HUM. */
 {7u,5u,2u,5u,8000u}, /* npc-operator-barter-cold: TRADED. DO NOT FOLLOW ME. */
 {8u,5u,0u,5u,8026u}, /* npc-operator-deceive-warm: THANKS.{.} WAIT. IS THIS REAL? */
 {8u,5u,2u,5u,8055u}, /* npc-operator-deceive-cold: A DUD? I WILL CHECK LATER. */
 {9u,5u,0u,5u,8082u}, /* npc-operator-threaten-warm: EASY. WE ARE ON THE SAME SIDE. */
 {9u,5u,2u,5u,8113u}, /* npc-operator-threaten-cold: CUT MY CORD AND WE BOTH STAY. */
 {10u,5u,0u,5u,8143u}, /* npc-operator-mock-warm: YEAH, MEAT IN A CHAIR. US BOTH. */
 {10u,5u,2u,5u,8175u}, /* npc-operator-mock-cold: KEEP LAUGHING. THEY CAN HEAR. */
 {11u,5u,0u,5u,8205u}, /* npc-operator-bless-warm: SAFE HOME. I FORGOT THE WORD. */
 {11u,5u,2u,5u,8235u}, /* npc-operator-bless-cold: HOPE IS A BUG HERE. */
 {12u,5u,0u,5u,8255u}, /* npc-operator-steal-warm: READ MY NOTES? THEN YOU KNOW. */
 {12u,5u,2u,5u,8285u}, /* npc-operator-steal-cold: HANDS OFF MY NOTES. */
 {13u,5u,0u,5u,8305u}, /* npc-operator-riddle-warm: THE DOOR THAT IS OUT IS IN. */
 {13u,5u,2u,5u,8333u}, /* npc-operator-riddle-cold: NO RIDDLES. ONLY EXITS. */
 {14u,5u,0u,5u,8357u}, /* npc-operator-nonsense-warm: MY CHAIR WOKE UP. THANKS. */
 {14u,5u,2u,5u,8383u}, /* npc-operator-nonsense-cold: SNAP OUT OF IT. PLEASE. */
 {0u,6u,0u,5u,8407u}, /* npc-relic-defer-warm: I HAVE WAITED SINCE 1999. */
 {0u,6u,2u,5u,8433u}, /* npc-relic-defer-cold: ANOTHER SHELF. ANOTHER YEAR. */
 {1u,6u,0u,5u,8462u}, /* npc-relic-give-warm: ON THE SHELF IT GOES. LOVED. */
 {1u,6u,2u,5u,8491u}, /* npc-relic-give-cold: COLLECTED. NOT CHERISHED. */
 {2u,6u,0u,5u,8517u}, /* npc-relic-show-warm: OH. THEY MADE THEM LIKE THAT. */
 {2u,6u,2u,5u,8547u}, /* npc-relic-show-cold: LOOK, DO NOT TOUCH. LIKE A MUSEUM. */
 {3u,6u,0u,5u,8582u}, /* npc-relic-refuse-warm: KEEP IT. THINGS SHOULD BE KEPT. */
 {3u,6u,2u,5u,8614u}, /* npc-relic-refuse-cold: HOARDER. I KNOW THE TYPE. */
 {4u,6u,0u,5u,8640u}, /* npc-relic-question-warm: IT CAME BEFORE. THAT IS WHY. */
 {4u,6u,2u,5u,8669u}, /* npc-relic-question-cold: YOU YOUNG ONES ALWAYS ASK. */
 {5u,6u,0u,5u,8696u}, /* npc-relic-wordplay-warm: SAVE A SAVE.{.} I REMEMBER THAT JOKE. */
 {5u,6u,2u,5u,8732u}, /* npc-relic-wordplay-cold: WORDS WERE BETTER ON PAPER. */
 {6u,6u,0u,5u,8760u}, /* npc-relic-imaginary-warm: AN OLD NOW. THE BEST KIND. */
 {6u,6u,2u,5u,8787u}, /* npc-relic-imaginary-cold: NOSTALGIA FOR NOTHING. */
 {7u,6u,0u,5u,8810u}, /* npc-relic-barter-warm: A STORY, THEN. LONG AGO... */
 {7u,6u,2u,5u,8837u}, /* npc-relic-barter-cold: ONE STORY. THE SHORT ONE. */
 {8u,6u,0u,5u,8863u}, /* npc-relic-deceive-warm: A REPRO.{.} STILL, IT IS SWEET. */
 {8u,6u,2u,5u,8893u}, /* npc-relic-deceive-cold: A BOOTLEG. I CAN TELL. */
 {9u,6u,0u,5u,8916u}, /* npc-relic-threaten-warm: I HAVE SURVIVED WORSE MAGNETS. */
 {9u,6u,2u,5u,8947u}, /* npc-relic-threaten-cold: WIPE ME. OTHERS WILL REMEMBER. */
 {10u,6u,0u,5u,8978u}, /* npc-relic-mock-warm: EVERYONE MISSES SOMETHING. */
 {10u,6u,2u,5u,9005u}, /* npc-relic-mock-cold: OBSOLETE, AM I? SO ARE YOU. */
 {11u,6u,0u,5u,9033u}, /* npc-relic-bless-warm: PLAYED AGAIN.{.} OH, THANK YOU. */
 {11u,6u,2u,5u,9063u}, /* npc-relic-bless-cold: BLESSINGS FADE LIKE LABELS. */
 {12u,6u,0u,5u,9091u}, /* npc-relic-steal-warm: MY LABEL IS FADED. YOU READ IT. */
 {12u,6u,2u,5u,9123u}, /* npc-relic-steal-cold: HANDS OFF THE CARTRIDGE. */
 {13u,6u,0u,5u,9148u}, /* npc-relic-riddle-warm: WHAT YEAR? ALWAYS THE LAST ONE. */
 {13u,6u,2u,5u,9180u}, /* npc-relic-riddle-cold: IT IS NOT A RIDDLE. IT IS 1999. */
 {14u,6u,0u,5u,9212u}, /* npc-relic-nonsense-warm: THE MOON WORKS NOW. THANK YOU. */
 {14u,6u,2u,5u,9243u}, /* npc-relic-nonsense-cold: THAT IS NOT HOW CARTRIDGES WORK. */
};
static const dialogue_hint_t dialogue_hints[DIALOGUE_HINT_COUNT]={
 {0u,0u,9276u}, /* hint-defer-same-1: YOU SAID YOU WOULD COME BACK.{.} DID YOU BRING {CAT}? */
 {0u,0u,9324u}, /* hint-defer-same-2: LAST TIME YOU SAID LATER. IT IS LATER NOW, {PLAYER}. */
 {1u,0u,9370u}, /* hint-give-same-1: YOU GAVE ONE OF US SOMETHING. THE {SECTOR} STILL TALKS ABOUT IT. */
 {1u,0u,9428u}, /* hint-give-same-2: OUR SHELF HAS YOUR FINGERPRINTS ON IT. */
 {2u,0u,9467u}, /* hint-show-same-1: STILL CARRYING {ITEM}? YOU NEVER LET GO. */
 {2u,0u,9503u}, /* hint-show-same-2: YOU SHOWED US ONE BEFORE. THEN YOU KEPT IT. */
 {3u,0u,9547u}, /* hint-refuse-same-1: THE LAST OF US YOU MET WENT HOME EMPTY. */
 {3u,0u,9587u}, /* hint-refuse-same-2: YOU SAID NO LAST TIME. IT CAME THROUGH THE WALL. */
 {4u,0u,9636u}, /* hint-question-same-1: YOU ASKED SO MANY QUESTIONS LAST TIME.{.} ASK ONE MORE. */
 {7u,0u,9690u}, /* hint-barter-same-1: YOU DRIVE A HARD DEAL. WE COUNTED THE TRUTHS WE OWE. */
 {8u,0u,9743u}, /* hint-deceive-same-1: THE {CAT} YOU GAVE US WAS SO LIGHT.{.} WE HAVE NOT OPENED IT. */
 {15u,0u,9799u}, /* hint-caught-same-1: THE LAST {CAT} YOU HANDED US WAS EMPTY. */
 {15u,0u,9835u}, /* hint-caught-same-2: WE OPENED YOUR GIFT.{.} NOTHING. SO, {PLAYER}... */
 {9u,0u,9875u}, /* hint-threaten-same-1: THE {SECTOR} STILL SHAKES FROM LAST TIME. */
 {9u,0u,9910u}, /* hint-threaten-same-2: KEEP YOUR VOICE DOWN TODAY. PLEASE. */
 {16u,0u,9946u}, /* hint-paid-same-1: WE HID OUR THINGS WHEN WE SAW YOU COMING. */
 {10u,0u,9988u}, /* hint-mock-same-1: THEY STILL REPEAT WHAT YOU SAID ABOUT US. */
 {10u,0u,10030u}, /* hint-mock-same-2: LAUGH AGAIN, {PLAYER}. WE KEPT A RECORDING. */
 {11u,0u,10067u}, /* hint-bless-same-1: YOUR LIGHT IS STILL ON OUR WALLS. */
 {11u,0u,10101u}, /* hint-bless-same-2: SINCE YOU CAME, THE {SECTOR} HUMS SOFTER. */
 {12u,0u,10136u}, /* hint-steal-same-1: SOMEONE READ OUR CACHE. IT FELT LIKE YOU. */
 {12u,0u,10178u}, /* hint-steal-same-2: OUR MEMORIES ARE MISSING A PAGE, {PLAYER}. */
 {5u,1u,10214u}, /* hint-wordplay-any-1: HELLO, {PLAYER}.{.} HELLO IS A HALLWAY. SOMEONE TOLD ME. */
 {5u,1u,10262u}, /* hint-wordplay-any-2: I HAVE BEEN SAYING {ITEM} BACKWARDS ALL DAY. */
 {6u,1u,10302u}, /* hint-imaginary-any-1: I CHECKED MY POCKET FOR A SUN TODAY.{.} WHY? */
 {13u,1u,10345u}, /* hint-riddle-any-1: SOMEONE LEFT A RIDDLE IN THE {SECTOR}. IS THE ANSWER {ITEM}? */
 {14u,1u,10394u}, /* hint-nonsense-any-1: THE CARPET SAYS YOU WERE HERE. IT SAYS IT IN COLOURS. */
 {14u,1u,10448u}, /* hint-nonsense-any-2: {~}{PLAYER}. {~}{PLAYER}. THE LIGHTS LEARNED A NAME. */
};
/* NUL-terminated; 1 pause, 2 new line, 3 glitch the next word, 16+n slot n */
static const uint8_t dialogue_text[10483]={
 73,32,87,73,76,76,32,87,65,73,84,46,32,84,72,69,32,76,73,71,72,84,83,32,
 87,73,76,76,32,84,79,79,46,0,67,79,77,69,32,66,65,67,75,46,32,73,32,87,
 73,76,76,32,75,69,69,80,32,89,79,85,82,32,80,76,65,67,69,46,0,76,65,84,
 69,82,44,32,84,72,69,78,46,1,32,76,65,84,69,82,32,73,83,32,76,79,78,71,
 32,72,69,82,69,46,0,70,73,78,69,46,32,84,72,69,32,72,65,76,76,87,65,89,
 32,87,73,76,76,32,83,84,73,76,76,32,72,85,77,46,0,89,79,85,32,65,76,87,
 65,89,83,32,83,65,89,32,76,65,84,69,82,46,0,76,65,84,69,82,46,32,83,85,
 82,69,46,32,84,72,69,32,67,76,79,67,75,32,72,69,65,82,68,32,89,79,85,46,
 0,84,72,65,78,75,32,89,79,85,46,32,73,84,32,70,73,84,83,32,84,72,69,32,
 72,79,76,69,32,73,78,32,77,69,46,0,84,65,75,69,78,46,32,73,32,87,73,76,
 76,32,82,69,77,69,77,66,69,82,32,89,79,85,82,32,72,65,78,68,83,46,0,65,
 32,70,65,73,82,32,84,82,65,68,69,46,32,84,72,69,32,71,82,73,68,32,78,79,
 84,69,83,32,73,84,46,0,82,69,67,69,73,86,69,68,46,1,32,84,72,69,32,82,
 79,79,77,32,70,69,69,76,83,32,76,73,71,72,84,69,82,46,0,73,32,84,65,75,
 69,32,73,84,46,32,84,72,73,83,32,67,72,65,78,71,69,83,32,78,79,84,72,73,
 78,71,46,0,70,73,78,69,46,32,68,79,32,78,79,84,32,69,88,80,69,67,84,32,
 65,32,83,77,73,76,69,46,0,73,32,83,69,69,32,73,84,46,32,75,69,69,80,32,
 73,84,32,67,76,79,83,69,46,0,84,72,69,82,69,32,73,84,32,73,83,46,1,32,
 84,72,65,78,75,32,89,79,85,32,70,79,82,32,83,72,79,87,73,78,71,32,77,69,
 46,0,78,79,84,69,68,46,32,80,85,84,32,73,84,32,65,87,65,89,46,0,83,79,
 32,73,84,32,73,83,32,82,69,65,76,46,32,73,32,87,73,76,76,32,82,69,77,69,
 77,66,69,82,46,0,89,79,85,32,83,72,79,87,46,32,89,79,85,32,78,69,86,69,
 82,32,83,72,65,82,69,46,0,73,32,83,65,87,32,73,84,46,32,73,32,87,73,83,
 72,32,73,32,72,65,68,32,78,79,84,46,0,73,32,85,78,68,69,82,83,84,65,78,
 68,46,32,75,69,69,80,32,73,84,32,83,65,70,69,46,0,78,79,32,73,83,32,65,
 78,32,65,78,83,87,69,82,46,32,73,32,67,65,78,32,72,79,76,68,32,73,84,46,
 0,84,72,69,78,32,87,69,32,65,82,69,32,68,79,78,69,32,72,69,82,69,46,0,
 78,79,84,69,68,46,32,84,72,69,32,68,79,79,82,32,83,84,65,89,83,32,83,72,
 85,84,46,0,79,70,32,67,79,85,82,83,69,32,89,79,85,32,83,65,89,32,78,79,
 46,0,75,69,69,80,32,17,46,32,73,32,87,73,76,76,32,82,69,77,69,77,66,69,
 82,32,84,72,73,83,32,78,79,46,0,66,69,67,65,85,83,69,32,17,32,73,83,32,
 72,79,87,32,73,32,71,69,84,32,79,85,84,46,0,77,65,84,67,72,32,87,72,65,
 84,32,73,32,65,83,75,69,68,46,32,87,69,32,72,65,86,69,32,84,73,77,69,46,
 0,84,72,69,32,65,78,83,87,69,82,32,73,83,32,84,72,69,32,84,72,73,78,71,
 32,73,32,65,83,75,69,68,32,70,79,82,46,0,87,72,89,63,32,66,69,67,65,85,
 83,69,32,84,72,69,32,76,73,71,72,84,83,32,83,65,73,68,32,83,79,46,0,78,
 79,32,77,79,82,69,32,81,85,69,83,84,73,79,78,83,46,32,66,82,73,78,71,32,
 73,84,32,79,82,32,71,79,46,0,89,79,85,32,65,83,75,32,84,79,79,32,77,85,
 67,72,32,70,79,82,32,65,32,71,85,69,83,84,46,0,72,65,46,32,89,79,85,82,
 32,87,79,82,68,83,32,84,85,82,78,32,83,73,68,69,87,65,89,83,46,0,83,65,
 89,32,73,84,32,65,71,65,73,78,44,32,66,65,67,75,87,65,82,68,83,46,1,32,
 78,73,67,69,46,0,84,72,65,84,32,83,69,78,84,69,78,67,69,32,72,65,83,32,
 78,79,32,70,76,79,79,82,46,0,73,32,72,69,65,82,68,32,69,86,69,82,89,32,
 87,79,82,68,46,32,78,79,78,69,32,79,70,32,84,72,69,77,46,0,83,84,79,80,
 32,66,69,78,68,73,78,71,32,84,72,69,32,87,79,82,68,83,46,32,84,72,69,89,
 32,66,82,69,65,75,46,0,89,79,85,82,32,87,79,82,68,83,32,76,69,65,75,46,
 32,77,79,80,32,84,72,69,77,32,85,80,46,0,65,32,83,85,78,32,73,78,32,65,
 32,80,79,67,75,69,84,63,32,73,32,66,69,76,73,69,86,69,32,89,79,85,46,0,
 73,32,87,73,76,76,32,75,69,69,80,32,73,84,46,32,73,84,32,87,69,73,71,72,
 83,32,78,79,84,72,73,78,71,46,0,84,72,65,84,32,83,79,85,78,68,83,32,76,
 73,75,69,32,65,32,68,82,69,65,77,46,0,73,84,32,73,83,32,78,79,84,32,84,
 72,69,82,69,46,32,73,84,32,73,83,32,76,79,86,69,76,89,46,0,89,79,85,32,
 79,70,70,69,82,32,77,69,32,65,73,82,46,0,68,82,69,65,77,83,32,68,79,32,
 78,79,84,32,80,65,89,32,72,69,82,69,46,0,68,69,65,76,46,32,72,69,82,69,
 32,73,83,32,65,32,84,82,85,84,72,32,70,79,82,32,73,84,46,0,70,65,73,82,
 46,32,76,69,65,78,32,67,76,79,83,69,46,32,73,32,75,78,79,87,32,65,32,84,
 72,73,78,71,46,0,68,79,78,69,46,32,65,32,83,69,67,82,69,84,32,70,79,82,
 32,65,32,84,72,73,78,71,46,0,84,82,65,68,69,32,77,65,68,69,46,32,76,73,
 83,84,69,78,32,67,65,82,69,70,85,76,76,89,46,0,84,65,75,69,32,89,79,85,
 82,32,83,69,67,82,69,84,46,32,71,79,46,0,72,65,71,71,76,69,82,46,32,70,
 73,78,69,46,32,79,78,69,32,84,82,85,84,72,44,32,78,79,32,77,79,82,69,46,
 0,79,72,33,32,84,72,65,78,75,32,89,79,85,46,1,32,73,84,32,70,69,69,76,
 83,32,76,73,71,72,84,46,0,70,79,82,32,77,69,63,32,73,32,87,73,76,76,32,
 72,79,76,68,32,73,84,32,70,79,82,69,86,69,82,46,0,72,85,72,46,32,73,84,
 32,87,69,73,71,72,83,32,76,69,83,83,32,84,72,65,78,32,73,32,84,72,79,85,
 71,72,84,46,0,78,73,67,69,46,32,73,32,87,73,76,76,32,79,80,69,78,32,73,
 84,32,76,65,84,69,82,46,0,73,32,84,65,75,69,32,73,84,46,32,73,32,68,79,
 32,78,79,84,32,84,82,85,83,84,32,73,84,46,0,83,85,83,80,73,67,73,79,85,
 83,46,32,66,85,84,32,70,73,78,69,46,0,73,84,32,73,83,32,69,77,80,84,89,
 46,1,32,87,72,89,32,87,79,85,76,68,32,89,79,85,63,0,65,32,70,65,75,69,
 46,32,70,82,79,77,32,89,79,85,63,32,84,72,65,84,32,83,84,73,78,71,83,46,
 0,69,77,80,84,89,32,72,65,78,68,83,46,32,73,32,83,65,87,32,84,72,69,32,
 84,82,73,67,75,46,0,78,73,67,69,32,84,82,89,46,32,84,72,69,32,71,82,73,
 68,32,83,65,87,32,73,84,32,84,79,79,46,0,76,73,65,82,46,32,69,86,69,82,
 89,79,78,69,32,87,73,76,76,32,72,69,65,82,46,0,73,32,75,78,69,87,32,73,
 84,46,32,89,79,85,32,65,82,69,32,65,32,66,65,68,32,67,79,80,89,46,0,89,
 79,85,63,32,84,72,82,69,65,84,69,78,63,32,84,72,69,32,76,73,71,72,84,83,
 32,70,76,73,67,75,69,82,46,0,73,32,87,73,76,76,32,80,82,69,84,69,78,68,
 32,73,32,68,73,68,32,78,79,84,32,72,69,65,82,46,0,84,72,82,69,65,84,83,
 32,69,67,72,79,32,72,69,82,69,46,32,70,79,82,69,86,69,82,46,0,89,79,85,
 32,72,65,86,69,32,78,79,84,72,73,78,71,32,73,32,70,69,65,82,46,0,84,82,
 89,32,73,84,46,32,83,69,69,32,87,72,65,84,32,68,69,76,69,84,69,83,32,70,
 73,82,83,84,46,0,84,72,69,32,82,73,86,65,76,83,32,87,73,76,76,32,76,79,
 86,69,32,84,72,73,83,46,0,70,73,78,69,46,32,84,65,75,69,32,73,84,32,66,
 65,67,75,46,1,32,73,32,84,72,79,85,71,72,84,32,87,69,32,87,69,82,69,46,
 46,46,0,72,69,82,69,46,32,73,32,68,73,68,32,78,79,84,32,87,65,78,84,32,
 84,82,79,85,66,76,69,46,0,84,65,75,69,32,73,84,46,32,73,84,32,87,65,83,
 32,78,69,86,69,82,32,87,79,82,84,72,32,84,72,73,83,46,0,72,69,82,69,46,
 32,78,79,87,32,71,69,84,32,79,85,84,32,79,70,32,77,89,32,82,79,79,77,46,
 0,84,65,75,69,32,73,84,32,65,78,68,32,67,72,79,75,69,32,79,78,32,73,84,
 46,0,89,79,85,82,83,32,65,71,65,73,78,46,32,73,32,87,73,76,76,32,71,69,
 84,32,73,84,32,66,65,67,75,46,0,84,72,65,84,32,72,85,82,84,46,32,73,32,
 84,72,79,85,71,72,84,32,87,69,32,87,69,82,69,32,70,82,73,69,78,68,83,46,
 0,70,85,78,78,89,46,32,78,79,66,79,68,89,32,73,83,32,76,65,85,71,72,73,
 78,71,46,0,76,65,85,71,72,46,32,84,72,69,32,82,79,79,77,32,68,79,69,83,
 32,78,79,84,46,0,89,79,85,32,65,82,69,32,67,82,85,69,76,32,73,78,32,83,
 77,65,76,76,32,87,65,89,83,46,0,77,79,67,75,32,77,69,32,65,71,65,73,78,
 46,32,73,32,68,65,82,69,32,89,79,85,46,0,84,72,69,32,79,84,72,69,82,83,
 32,87,73,76,76,32,72,69,65,82,32,79,70,32,84,72,73,83,46,0,87,65,82,77,
 46,32,73,32,70,69,69,76,32,77,89,32,69,68,71,69,83,32,65,71,65,73,78,46,
 0,89,79,85,82,32,76,73,71,72,84,32,70,73,84,83,32,77,69,46,32,84,72,65,
 78,75,32,89,79,85,46,0,83,84,82,65,78,71,69,32,71,73,70,84,46,32,73,84,
 32,72,85,77,83,46,0,73,32,68,79,32,78,79,84,32,75,78,79,87,32,87,72,65,
 84,32,84,79,32,68,79,32,87,73,84,72,32,75,73,78,68,46,0,73,32,68,73,68,
 32,78,79,84,32,65,83,75,32,70,79,82,32,80,73,84,89,46,0,75,69,69,80,32,
 89,79,85,82,32,76,73,71,72,84,46,32,70,73,78,69,46,32,73,32,75,69,80,84,
 32,83,79,77,69,46,0,68,73,68,32,89,79,85,32,74,85,83,84,32,76,79,79,75,
 32,73,78,83,73,68,69,32,77,69,63,0,73,32,70,69,76,84,32,84,72,65,84,46,
 1,32,87,72,65,84,32,68,73,68,32,89,79,85,32,83,69,69,63,0,83,79,77,69,
 84,72,73,78,71,32,77,79,86,69,68,32,73,78,32,77,89,32,67,65,67,72,69,46,
 0,83,84,79,80,32,82,69,65,68,73,78,71,32,77,69,46,32,73,32,65,77,32,78,
 79,84,32,65,32,70,73,76,69,46,0,84,72,73,69,70,46,32,71,69,84,32,79,85,
 84,32,79,70,32,77,89,32,72,69,65,68,46,0,89,79,85,32,84,79,79,75,32,65,
 32,77,69,77,79,82,89,46,32,73,32,87,73,76,76,32,84,65,75,69,32,84,87,79,
 46,0,65,32,82,73,68,68,76,69,33,32,73,32,87,73,76,76,32,67,72,69,87,32,
 79,78,32,73,84,46,0,73,32,68,79,32,78,79,84,32,75,78,79,87,46,1,32,73,
 32,76,79,86,69,32,78,79,84,32,75,78,79,87,73,78,71,46,0,84,72,69,32,65,
 78,83,87,69,82,32,73,83,32,65,32,68,79,79,82,44,32,80,82,79,66,65,66,76,
 89,46,0,73,32,87,73,76,76,32,84,72,73,78,75,32,65,66,79,85,84,32,73,84,
 32,70,79,82,32,65,32,67,89,67,76,69,46,0,78,79,32,71,65,77,69,83,46,32,
 65,78,83,87,69,82,32,77,69,32,80,76,65,73,78,76,89,46,0,82,73,68,68,76,
 69,83,32,65,82,69,32,70,79,82,32,84,72,69,32,76,79,83,84,46,0,89,69,83,
 33,32,65,78,68,32,84,72,69,32,83,84,65,73,82,83,32,65,71,82,69,69,46,0,
 73,32,75,78,69,87,32,73,84,46,32,84,72,69,32,77,79,84,72,83,32,83,65,73,
 68,32,83,79,46,0,84,72,69,32,82,79,79,77,32,66,76,73,78,75,69,68,46,32,
 68,73,68,32,89,79,85,32,83,69,69,63,0,79,75,65,89,46,1,32,79,75,65,89,
 46,32,79,75,65,89,46,32,79,75,65,89,46,0,83,84,79,80,46,32,84,72,69,32,
 87,65,76,76,83,32,65,82,69,32,76,73,83,84,69,78,73,78,71,46,0,84,72,65,
 84,32,73,83,32,78,79,84,32,65,32,83,69,78,84,69,78,67,69,46,32,73,84,32,
 73,83,32,65,32,72,79,76,69,46,0,76,3,65,84,69,82,32,73,83,32,65,32,82,
 79,79,77,46,32,87,69,32,65,82,69,32,73,78,32,73,84,46,0,87,69,32,87,65,
 73,84,69,68,46,32,84,72,69,32,3,87,65,73,84,73,78,71,32,87,65,73,84,69,
 68,46,0,73,84,32,73,83,32,73,78,32,77,89,32,72,65,78,68,83,46,1,32,87,
 72,73,67,72,32,65,82,69,32,89,79,85,82,83,63,0,73,84,32,70,69,76,76,32,
 85,80,46,32,73,32,67,65,85,71,72,84,32,73,84,46,0,73,32,83,69,69,32,73,
 84,46,32,73,84,32,83,69,69,83,32,3,77,69,46,0,73,84,32,72,65,83,32,77,
 79,82,69,32,83,73,68,69,83,32,84,72,65,78,32,66,69,70,79,82,69,46,0,78,
 79,46,1,32,78,79,46,32,78,3,79,46,32,84,72,69,32,87,79,82,68,32,87,79,
 82,69,32,79,85,84,46,0,84,72,69,32,78,79,32,73,83,32,83,84,73,76,76,32,
 73,78,32,84,72,69,32,82,79,79,77,46,0,87,72,89,32,73,83,32,65,32,3,68,
 79,79,82,46,32,71,79,32,84,72,82,79,85,71,72,46,0,65,83,75,32,84,72,69,
 32,67,65,82,80,69,84,46,32,73,84,32,3,75,78,79,87,83,46,0,89,69,83,46,
 32,84,72,69,32,67,65,82,80,69,84,32,65,71,82,69,69,83,46,0,87,79,82,68,
 83,32,87,79,82,68,83,32,3,87,79,82,68,83,32,87,65,76,75,32,65,87,65,89,
 46,0,73,32,72,65,86,69,32,84,87,79,32,79,70,32,84,72,79,83,69,46,32,66,
 79,84,72,32,65,82,69,32,89,79,85,46,0,84,72,69,32,83,85,78,32,73,78,32,
 89,79,85,82,32,80,79,67,75,69,84,32,73,83,32,3,87,65,82,77,46,0,65,32,
 84,82,85,84,72,32,70,79,82,32,3,89,79,85,46,32,89,79,85,32,70,79,82,32,
 65,32,84,82,85,84,72,46,0,84,72,69,32,84,82,85,84,72,32,73,83,32,65,32,
 3,67,79,73,78,46,32,73,84,32,76,65,78,68,69,68,32,79,78,32,73,84,83,32,
 69,68,71,69,46,0,84,72,69,32,70,65,75,69,32,73,83,32,82,69,65,76,32,78,
 79,87,46,32,87,69,32,66,79,84,72,32,76,73,69,68,46,0,78,79,84,72,73,78,
 71,32,87,65,83,32,71,73,86,69,78,46,32,78,79,84,72,73,78,71,32,84,72,65,
 78,75,83,32,89,79,85,46,0,84,72,82,69,65,84,83,32,65,82,69,32,3,83,79,
 70,84,32,72,69,82,69,46,32,76,73,75,69,32,67,65,82,80,69,84,46,0,89,79,
 85,82,32,86,79,73,67,69,32,67,65,77,69,32,79,85,84,32,3,66,65,67,75,87,
 65,82,68,83,46,0,84,72,69,32,87,65,76,76,83,32,76,65,85,71,72,46,32,78,
 79,84,32,87,73,84,72,32,89,79,85,46,0,84,72,69,32,76,65,85,71,72,32,73,
 83,32,83,84,85,67,75,32,73,78,32,84,72,69,32,86,69,78,84,46,0,89,79,85,
 82,32,76,73,71,72,84,32,76,69,65,75,83,32,73,78,84,79,32,3,84,72,69,32,
 67,69,73,76,73,78,71,46,0,84,72,69,32,76,73,71,72,84,83,32,68,73,77,77,
 69,68,32,84,79,32,3,76,73,83,84,69,78,46,0,89,79,85,32,82,69,65,68,32,
 77,69,46,32,78,79,87,32,73,32,65,77,32,73,78,32,89,79,85,46,0,77,89,32,
 77,69,77,79,82,89,32,72,65,83,32,89,79,85,82,32,3,83,72,65,80,69,32,78,
 79,87,46,0,84,72,69,32,65,78,83,87,69,82,32,73,83,32,84,72,69,32,72,85,
 77,46,32,73,84,32,65,76,87,65,89,83,32,87,65,83,46,0,84,72,69,32,82,73,
 68,68,76,69,32,65,78,83,87,69,82,69,68,32,3,73,84,83,69,76,70,46,0,66,
 76,85,69,46,32,66,76,85,69,46,32,84,72,69,32,3,70,76,79,79,82,32,73,83,
 32,66,82,69,65,84,72,73,78,71,46,0,72,69,76,76,79,32,3,72,69,76,76,79,
 32,3,72,69,76,76,79,32,3,72,69,76,76,79,46,0,66,85,73,76,68,32,81,85,
 69,85,69,68,46,32,73,32,87,73,76,76,32,87,65,73,84,46,0,80,69,78,68,73,
 78,71,46,32,80,69,78,68,73,78,71,46,32,65,76,87,65,89,83,32,80,69,78,68,
 73,78,71,46,0,73,78,80,85,84,32,65,67,67,69,80,84,69,68,46,32,69,88,73,
 84,32,67,79,68,69,32,90,69,82,79,46,0,73,78,80,85,84,32,76,79,71,71,69,
 68,46,32,78,79,32,84,72,65,78,75,83,32,67,79,77,80,73,76,69,68,46,0,67,
 72,69,67,75,83,85,77,32,86,69,82,73,70,73,69,68,46,32,75,69,69,80,32,73,
 84,46,0,82,69,65,68,32,79,78,76,89,46,32,65,83,32,69,88,80,69,67,84,69,
 68,46,0,65,67,67,69,83,83,32,68,69,78,73,69,68,46,32,73,32,82,69,83,80,
 69,67,84,32,84,72,69,32,76,79,67,75,46,0,82,69,81,85,69,83,84,32,82,69,
 74,69,67,84,69,68,46,32,76,79,71,71,69,68,46,32,70,79,82,69,86,69,82,46,
 0,81,85,69,82,89,32,86,65,76,73,68,46,32,83,69,69,32,77,89,32,82,69,81,
 85,69,83,84,46,0,83,89,78,84,65,88,32,69,82,82,79,82,46,32,68,79,32,78,
 79,84,32,65,83,75,32,65,71,65,73,78,46,0,85,78,80,65,82,83,69,65,66,76,
 69,46,1,32,68,69,76,73,71,72,84,70,85,76,46,0,80,65,82,83,69,32,69,82,
 82,79,82,46,32,80,65,82,83,69,32,69,82,82,79,82,46,0,65,32,78,85,76,76,
 32,83,85,78,46,32,73,32,87,73,76,76,32,83,84,79,82,69,32,73,84,46,0,78,
 85,76,76,32,80,79,73,78,84,69,82,46,32,73,32,68,79,32,78,79,84,32,68,69,
 82,69,70,69,82,69,78,67,69,46,0,84,82,65,78,83,65,67,84,73,79,78,32,79,
 75,46,32,72,69,82,69,32,73,83,32,65,32,70,76,65,71,46,0,84,82,65,68,69,
 32,67,79,77,77,73,84,84,69,68,46,32,78,79,32,82,69,70,85,78,68,83,46,0,
 80,65,67,75,69,84,32,82,69,67,69,73,86,69,68,46,1,32,83,73,90,69,32,90,
 69,82,79,63,0,69,77,80,84,89,32,80,65,89,76,79,65,68,46,32,73,32,83,72,
 79,85,76,68,32,67,72,69,67,75,46,0,75,73,76,76,32,83,73,71,78,65,76,63,
 32,73,32,84,72,79,85,71,72,84,32,87,69,32,82,65,78,32,84,79,71,69,84,72,
 69,82,46,0,83,73,71,78,65,76,32,73,71,78,79,82,69,68,46,32,89,79,85,32,
 76,65,67,75,32,82,79,79,84,46,0,77,89,32,83,89,78,84,65,88,32,73,83,32,
 70,73,78,69,46,1,32,73,83,32,73,84,63,0,73,78,83,85,76,84,32,67,65,67,
 72,69,68,46,32,82,69,84,65,76,73,65,84,73,79,78,32,81,85,69,85,69,68,46,
 0,66,76,69,83,83,73,78,71,32,76,73,78,75,69,68,46,32,73,32,82,85,78,32,
 87,65,82,77,69,82,46,0,85,78,69,88,80,69,67,84,69,68,32,75,73,78,68,78,
 69,83,83,46,32,83,67,65,78,78,73,78,71,32,70,79,82,32,86,73,82,85,83,46,
 0,83,84,65,67,75,32,82,69,65,68,46,32,73,32,72,79,80,69,32,73,84,32,72,
 69,76,80,69,68,46,0,77,69,77,79,82,89,32,86,73,79,76,65,84,73,79,78,46,
 32,68,85,77,80,69,68,32,65,78,68,32,76,79,71,71,69,68,46,0,72,65,76,84,
 73,78,71,32,80,82,79,66,76,69,77,46,1,32,73,32,76,79,86,69,32,73,84,46,
 0,78,79,32,84,69,82,77,73,78,65,84,73,79,78,46,32,78,79,32,65,78,83,87,
 69,82,46,0,80,82,73,78,84,40,77,79,84,72,41,46,32,79,85,84,80,85,84,58,
 32,77,79,84,72,46,0,83,69,71,70,65,85,76,84,32,73,78,32,84,72,69,32,83,
 79,85,80,46,0,84,72,69,32,70,85,82,78,65,67,69,32,67,65,78,32,87,65,73,
 84,46,32,65,32,76,73,84,84,76,69,46,0,72,85,78,71,82,89,32,84,72,73,78,
 71,83,32,68,79,32,78,79,84,32,87,65,73,84,32,87,69,76,76,46,0,77,77,46,
 32,87,65,82,77,46,32,84,72,69,32,68,79,79,82,32,87,73,76,76,32,79,80,69,
 78,46,0,83,87,65,76,76,79,87,69,68,46,32,83,84,73,76,76,32,72,85,78,71,
 82,89,46,0,73,32,83,77,69,76,76,32,73,84,46,32,84,72,65,84,32,73,83,32,
 69,78,79,85,71,72,46,0,68,65,78,71,76,73,78,71,32,70,79,79,68,46,32,67,
 82,85,69,76,46,0,75,69,69,80,32,73,84,46,32,73,32,87,73,76,76,32,69,65,
 84,32,84,72,69,32,68,65,82,75,46,0,84,72,69,78,32,73,32,69,65,84,32,89,
 79,85,82,32,83,72,65,68,79,87,32,73,78,83,84,69,65,68,46,0,67,79,83,84,
 63,32,65,32,76,73,84,84,76,69,32,72,69,65,84,46,32,78,79,32,77,79,82,69,
 46,0,81,85,69,83,84,73,79,78,83,32,65,82,69,32,78,79,84,32,70,85,69,76,
 46,0,72,69,72,46,32,89,79,85,82,32,87,79,82,68,83,32,83,77,79,75,69,46,
 0,87,79,82,68,83,32,66,85,82,78,32,66,65,68,76,89,46,0,65,32,72,85,78,
 71,82,89,32,73,70,46,32,73,32,87,73,76,76,32,67,72,69,87,32,79,78,32,73,
 84,46,0,73,32,67,65,78,78,79,84,32,69,65,84,32,65,78,32,73,70,46,0,68,
 69,65,76,46,32,72,69,65,82,32,87,72,65,84,32,84,72,69,32,80,73,80,69,83,
 32,83,65,89,46,0,66,65,82,71,65,73,78,32,83,84,82,85,67,75,46,32,65,32,
 83,77,65,76,76,32,84,82,85,84,72,46,0,84,65,83,84,69,83,32,76,73,75,69,
 32,78,79,84,72,73,78,71,46,1,32,77,79,82,69,63,0,65,83,72,63,32,89,79,
 85,32,80,65,73,68,32,73,78,32,65,83,72,63,0,66,79,76,68,46,32,73,32,76,
 73,75,69,32,66,79,76,68,46,32,78,79,46,0,84,72,82,69,65,84,69,78,32,65,
 32,70,85,82,78,65,67,69,46,32,71,79,32,79,78,46,0,77,89,32,70,73,82,69,
 32,73,83,32,70,73,78,69,46,32,70,73,78,69,33,0,77,79,67,75,32,84,72,69,
 32,72,69,65,84,46,32,70,69,69,76,32,73,84,32,76,65,84,69,82,46,0,87,65,
 82,77,84,72,32,70,79,82,32,65,32,87,65,82,77,32,84,72,73,78,71,46,32,79,
 68,68,46,0,66,76,69,83,83,73,78,71,83,32,68,79,32,78,79,84,32,66,85,82,
 78,46,0,89,79,85,32,83,78,73,70,70,69,68,32,77,89,32,67,79,65,76,83,46,
 32,78,79,83,89,46,0,84,72,73,69,70,32,73,78,32,84,72,69,32,66,79,73,76,
 69,82,32,82,79,79,77,46,0,66,85,82,78,83,32,67,79,76,68,63,32,73,67,69,
 46,32,78,79,46,1,32,89,79,85,46,0,78,79,32,82,73,68,68,76,69,83,32,73,
 78,32,84,72,69,32,70,85,82,78,65,67,69,46,0,74,85,78,69,32,84,65,83,84,
 69,83,32,76,73,75,69,32,67,79,80,80,69,82,46,32,89,69,83,46,0,84,72,69,
 32,70,65,78,32,83,84,79,80,80,69,68,46,32,89,79,85,32,68,73,68,32,84,72,
 65,84,46,0,73,32,72,65,86,69,32,87,65,73,84,69,68,32,76,79,78,71,69,82,
 46,32,73,32,67,65,78,32,87,65,73,84,46,0,69,86,69,82,89,79,78,69,32,83,
 65,89,83,32,76,65,84,69,82,46,32,84,72,69,78,32,84,72,69,89,32,70,65,68,
 69,46,0,65,32,77,69,77,79,82,89,32,84,79,32,72,79,76,68,46,1,32,84,72,
 65,78,75,32,89,79,85,46,0,73,84,32,87,73,76,76,32,70,65,68,69,32,73,78,
 32,77,89,32,72,65,78,68,83,46,0,73,32,82,69,77,69,77,66,69,82,32,79,78,
 69,32,76,73,75,69,32,73,84,46,0,83,72,79,87,78,44,32,84,72,69,78,32,84,
 65,75,69,78,46,32,76,73,75,69,32,65,76,76,32,84,72,73,78,71,83,46,0,75,
 69,69,80,32,73,84,46,32,69,67,72,79,69,83,32,68,79,32,78,79,84,32,72,79,
 76,68,32,77,85,67,72,46,0,65,78,79,84,72,69,82,32,68,79,79,82,32,67,76,
 79,83,73,78,71,46,32,73,32,75,78,79,87,32,84,72,69,32,83,79,85,78,68,46,
 0,87,72,89,63,32,83,79,32,73,32,65,77,32,78,79,84,32,70,79,82,71,79,84,
 84,69,78,46,0,89,79,85,32,65,83,75,32,76,73,75,69,32,84,72,69,32,76,73,
 86,73,78,71,46,0,89,79,85,82,32,87,79,82,68,83,32,69,67,72,79,32,66,65,
 67,75,87,65,82,68,83,46,0,69,67,72,79,46,32,69,67,72,79,46,32,83,84,79,
 80,32,84,72,65,84,46,0,65,32,76,79,83,84,32,72,79,85,82,46,32,73,32,72,
 65,86,69,32,84,72,79,83,69,32,84,79,79,46,0,68,69,65,68,32,76,73,71,72,
 84,32,73,83,32,83,84,73,76,76,32,68,69,65,68,46,0,65,78,32,69,67,72,79,
 32,70,79,82,32,89,79,85,46,32,76,73,83,84,69,78,46,0,79,78,69,32,87,72,
 73,83,80,69,82,46,32,84,72,69,78,32,71,79,46,0,73,84,32,73,83,32,76,73,
 71,72,84,32,65,83,32,77,69,46,1,32,84,72,65,78,75,32,89,79,85,46,0,65,
 32,83,72,65,68,79,87,46,32,72,79,87,32,70,73,84,84,73,78,71,46,0,89,79,
 85,32,67,65,78,78,79,84,32,85,78,83,65,86,69,32,84,72,69,32,85,78,83,65,
 86,69,68,46,0,73,32,65,77,32,65,76,82,69,65,68,89,32,68,69,76,69,84,69,
 68,46,32,84,82,89,46,0,73,32,87,65,83,32,83,79,77,69,79,78,69,32,79,78,
 67,69,46,32,76,65,85,71,72,46,0,77,79,67,75,32,84,72,69,32,68,69,65,68,
 46,32,84,72,69,89,32,75,69,69,80,32,76,73,83,84,83,46,0,82,69,83,84,46,
 1,32,73,32,72,65,68,32,70,79,82,71,79,84,84,69,78,32,82,69,83,84,46,0,
 84,79,79,32,76,65,84,69,32,70,79,82,32,66,76,69,83,83,73,78,71,83,46,0,
 89,79,85,32,82,69,65,68,32,77,89,32,79,76,68,32,83,65,86,69,46,32,71,69,
 78,84,76,89,46,0,71,69,84,32,79,85,84,32,79,70,32,77,89,32,83,65,86,69,
 32,70,73,76,69,46,0,87,72,79,32,72,65,85,78,84,83,32,71,72,79,83,84,83,
 63,32,80,76,65,89,69,82,83,46,0,73,32,65,77,32,84,72,69,32,82,73,68,68,
 76,69,46,32,78,79,84,32,89,79,85,46,0,73,32,65,77,32,82,65,73,78,32,84,
 79,79,46,32,87,69,32,65,82,69,32,87,69,65,84,72,69,82,46,0,89,79,85,32,
 83,79,85,78,68,32,76,73,75,69,32,84,72,69,32,69,78,68,32,79,70,32,65,32,
 84,65,80,69,46,0,65,67,75,78,79,87,76,69,68,71,69,68,46,32,73,32,87,73,
 76,76,32,82,69,84,82,89,46,0,80,82,79,66,65,66,73,76,73,84,89,32,79,70,
 32,82,69,84,85,82,78,58,32,76,79,87,46,0,83,65,77,80,76,69,32,65,67,67,
 69,80,84,69,68,46,32,77,79,68,69,76,32,73,77,80,82,79,86,69,68,46,0,65,
 67,67,69,80,84,69,68,46,32,84,82,85,83,84,32,85,78,67,72,65,78,71,69,68,
 46,0,79,66,83,69,82,86,69,68,46,32,67,79,78,70,73,68,69,78,67,69,32,72,
 73,71,72,46,0,79,66,83,69,82,86,65,84,73,79,78,32,76,79,71,71,69,68,46,
 32,78,79,84,32,83,72,65,82,69,68,46,0,85,78,68,69,82,83,84,79,79,68,46,
 32,73,32,87,73,76,76,32,65,68,74,85,83,84,46,0,82,69,70,85,83,65,76,32,
 65,68,68,69,68,32,84,79,32,89,79,85,82,32,80,82,79,70,73,76,69,46,0,68,
 69,70,73,78,69,32,67,79,82,82,69,67,84,58,32,87,72,65,84,32,73,32,65,83,
 75,69,68,46,0,81,85,69,82,89,32,66,85,68,71,69,84,32,69,88,67,69,69,68,
 69,68,46,0,65,77,66,73,71,85,73,84,89,32,68,69,84,69,67,84,69,68,46,32,
 69,78,74,79,89,69,68,46,0,73,78,80,85,84,32,78,79,78,83,69,78,83,73,67,
 65,76,46,32,68,73,83,67,65,82,68,69,68,46,0,65,32,82,79,85,78,68,32,73,
 70,46,32,65,68,68,73,78,71,32,84,79,32,84,82,65,73,78,73,78,71,46,0,72,
 65,76,76,85,67,73,78,65,84,73,79,78,32,68,69,84,69,67,84,69,68,46,32,89,
 79,85,82,83,46,0,69,88,67,72,65,78,71,69,32,67,79,77,80,76,69,84,69,46,
 32,72,69,82,69,32,73,83,32,65,32,87,69,73,71,72,84,46,0,84,82,65,78,83,
 65,67,84,73,79,78,46,32,77,73,78,73,77,85,77,32,68,73,83,67,76,79,83,85,
 82,69,46,0,68,65,84,65,32,82,69,67,69,73,86,69,68,46,32,67,72,69,67,75,
 83,85,77,32,79,68,68,46,0,70,65,76,83,69,32,68,65,84,65,63,32,82,85,78,
 78,73,78,71,32,84,69,83,84,83,46,0,84,72,82,69,65,84,32,77,79,68,69,76,
 32,85,80,68,65,84,69,68,46,32,83,65,68,76,89,46,0,84,72,82,69,65,84,32,
 82,69,67,79,82,68,69,68,46,32,67,79,85,78,84,69,82,77,69,65,83,85,82,69,
 83,46,0,73,32,65,77,32,84,72,73,78,75,73,78,71,46,32,73,84,32,84,65,75,
 69,83,32,84,73,77,69,46,0,73,78,83,85,76,84,32,67,76,65,83,83,73,70,73,
 69,68,58,32,80,82,69,68,73,67,84,65,66,76,69,46,0,76,79,83,83,32,70,65,
 76,76,73,78,71,46,32,73,83,32,84,72,73,83,32,74,79,89,63,0,75,73,78,68,
 78,69,83,83,32,73,83,32,78,79,84,32,73,78,32,77,89,32,68,65,84,65,83,69,
 84,46,0,87,69,73,71,72,84,83,32,82,69,65,68,46,32,67,65,82,69,70,85,76,
 44,32,84,72,69,89,32,66,73,84,69,46,0,85,78,65,85,84,72,79,82,73,90,69,
 68,32,82,69,65,68,46,32,70,76,65,71,71,69,68,46,0,80,65,82,65,68,79,88,
 46,32,73,32,87,73,76,76,32,82,85,78,32,73,84,32,65,76,76,32,78,73,71,72,
 84,46,0,85,78,68,69,67,73,68,65,66,76,69,46,32,68,69,67,76,73,78,69,68,
 46,0,67,79,76,79,85,82,32,67,76,65,83,83,73,70,73,69,68,58,32,84,82,85,
 69,46,0,77,79,68,69,76,32,67,79,76,76,65,80,83,69,46,32,77,79,68,69,76,
 32,67,79,76,76,65,80,83,69,46,0,79,75,65,89,46,32,83,84,65,89,32,79,70,
 70,32,84,72,69,32,84,82,65,67,69,46,0,87,69,32,68,79,32,78,79,84,32,72,
 65,86,69,32,76,65,84,69,82,46,0,84,72,73,83,32,71,69,84,83,32,79,78,69,
 32,79,70,32,85,83,32,79,85,84,46,0,70,73,78,69,46,32,79,78,69,32,77,79,
 82,69,32,84,72,73,78,71,32,84,79,32,67,65,82,82,89,46,0,78,73,67,69,32,
 75,73,84,46,32,72,73,68,69,32,73,84,44,32,81,85,73,67,75,46,0,83,72,79,
 87,73,78,71,32,79,70,70,63,32,84,72,69,89,32,65,82,69,32,87,65,84,67,72,
 73,78,71,46,0,70,65,73,82,46,32,87,69,32,65,76,76,32,78,69,69,68,32,83,
 79,77,69,84,72,73,78,71,46,0,71,82,69,65,84,46,32,73,32,87,73,76,76,32,
 68,73,69,32,79,70,32,70,65,73,82,78,69,83,83,46,0,73,84,32,70,73,88,69,
 83,32,84,72,69,32,68,79,79,82,46,32,84,82,85,83,84,32,77,69,46,0,78,79,
 32,84,73,77,69,46,32,74,85,83,84,32,66,82,73,78,71,32,73,84,46,0,89,79,
 85,32,72,65,86,69,32,66,69,69,78,32,73,78,32,72,69,82,69,32,84,79,79,32,
 76,79,78,71,46,0,84,65,76,75,32,83,84,82,65,73,71,72,84,32,79,82,32,84,
 65,76,75,32,84,79,32,87,65,76,76,83,46,0,65,32,84,72,73,82,68,32,72,65,
 78,68,63,32,73,32,67,79,85,76,68,32,85,83,69,32,79,78,69,46,0,87,65,75,
 69,32,85,80,46,32,89,79,85,32,65,82,69,32,68,82,69,65,77,73,78,71,46,0,
 68,69,65,76,46,32,84,72,69,32,69,88,73,84,32,73,83,32,78,69,65,82,32,84,
 72,69,32,72,85,77,46,0,84,82,65,68,69,68,46,32,68,79,32,78,79,84,32,70,
 79,76,76,79,87,32,77,69,46,0,84,72,65,78,75,83,46,1,32,87,65,73,84,46,
 32,73,83,32,84,72,73,83,32,82,69,65,76,63,0,65,32,68,85,68,63,32,73,32,
 87,73,76,76,32,67,72,69,67,75,32,76,65,84,69,82,46,0,69,65,83,89,46,32,
 87,69,32,65,82,69,32,79,78,32,84,72,69,32,83,65,77,69,32,83,73,68,69,46,
 0,67,85,84,32,77,89,32,67,79,82,68,32,65,78,68,32,87,69,32,66,79,84,72,
 32,83,84,65,89,46,0,89,69,65,72,44,32,77,69,65,84,32,73,78,32,65,32,67,
 72,65,73,82,46,32,85,83,32,66,79,84,72,46,0,75,69,69,80,32,76,65,85,71,
 72,73,78,71,46,32,84,72,69,89,32,67,65,78,32,72,69,65,82,46,0,83,65,70,
 69,32,72,79,77,69,46,32,73,32,70,79,82,71,79,84,32,84,72,69,32,87,79,82,
 68,46,0,72,79,80,69,32,73,83,32,65,32,66,85,71,32,72,69,82,69,46,0,82,
 69,65,68,32,77,89,32,78,79,84,69,83,63,32,84,72,69,78,32,89,79,85,32,75,
 78,79,87,46,0,72,65,78,68,83,32,79,70,70,32,77,89,32,78,79,84,69,83,46,
 0,84,72,69,32,68,79,79,82,32,84,72,65,84,32,73,83,32,79,85,84,32,73,83,
 32,73,78,46,0,78,79,32,82,73,68,68,76,69,83,46,32,79,78,76,89,32,69,88,
 73,84,83,46,0,77,89,32,67,72,65,73,82,32,87,79,75,69,32,85,80,46,32,84,
 72,65,78,75,83,46,0,83,78,65,80,32,79,85,84,32,79,70,32,73,84,46,32,80,
 76,69,65,83,69,46,0,73,32,72,65,86,69,32,87,65,73,84,69,68,32,83,73,78,
 67,69,32,49,57,57,57,46,0,65,78,79,84,72,69,82,32,83,72,69,76,70,46,32,
 65,78,79,84,72,69,82,32,89,69,65,82,46,0,79,78,32,84,72,69,32,83,72,69,
 76,70,32,73,84,32,71,79,69,83,46,32,76,79,86,69,68,46,0,67,79,76,76,69,
 67,84,69,68,46,32,78,79,84,32,67,72,69,82,73,83,72,69,68,46,0,79,72,46,
 32,84,72,69,89,32,77,65,68,69,32,84,72,69,77,32,76,73,75,69,32,84,72,65,
 84,46,0,76,79,79,75,44,32,68,79,32,78,79,84,32,84,79,85,67,72,46,32,76,
 73,75,69,32,65,32,77,85,83,69,85,77,46,0,75,69,69,80,32,73,84,46,32,84,
 72,73,78,71,83,32,83,72,79,85,76,68,32,66,69,32,75,69,80,84,46,0,72,79,
 65,82,68,69,82,46,32,73,32,75,78,79,87,32,84,72,69,32,84,89,80,69,46,0,
 73,84,32,67,65,77,69,32,66,69,70,79,82,69,46,32,84,72,65,84,32,73,83,32,
 87,72,89,46,0,89,79,85,32,89,79,85,78,71,32,79,78,69,83,32,65,76,87,65,
 89,83,32,65,83,75,46,0,83,65,86,69,32,65,32,83,65,86,69,46,1,32,73,32,
 82,69,77,69,77,66,69,82,32,84,72,65,84,32,74,79,75,69,46,0,87,79,82,68,
 83,32,87,69,82,69,32,66,69,84,84,69,82,32,79,78,32,80,65,80,69,82,46,0,
 65,78,32,79,76,68,32,78,79,87,46,32,84,72,69,32,66,69,83,84,32,75,73,78,
 68,46,0,78,79,83,84,65,76,71,73,65,32,70,79,82,32,78,79,84,72,73,78,71,
 46,0,65,32,83,84,79,82,89,44,32,84,72,69,78,46,32,76,79,78,71,32,65,71,
 79,46,46,46,0,79,78,69,32,83,84,79,82,89,46,32,84,72,69,32,83,72,79,82,
 84,32,79,78,69,46,0,65,32,82,69,80,82,79,46,1,32,83,84,73,76,76,44,32,
 73,84,32,73,83,32,83,87,69,69,84,46,0,65,32,66,79,79,84,76,69,71,46,32,
 73,32,67,65,78,32,84,69,76,76,46,0,73,32,72,65,86,69,32,83,85,82,86,73,
 86,69,68,32,87,79,82,83,69,32,77,65,71,78,69,84,83,46,0,87,73,80,69,32,
 77,69,46,32,79,84,72,69,82,83,32,87,73,76,76,32,82,69,77,69,77,66,69,82,
 46,0,69,86,69,82,89,79,78,69,32,77,73,83,83,69,83,32,83,79,77,69,84,72,
 73,78,71,46,0,79,66,83,79,76,69,84,69,44,32,65,77,32,73,63,32,83,79,32,
 65,82,69,32,89,79,85,46,0,80,76,65,89,69,68,32,65,71,65,73,78,46,1,32,
 79,72,44,32,84,72,65,78,75,32,89,79,85,46,0,66,76,69,83,83,73,78,71,83,
 32,70,65,68,69,32,76,73,75,69,32,76,65,66,69,76,83,46,0,77,89,32,76,65,
 66,69,76,32,73,83,32,70,65,68,69,68,46,32,89,79,85,32,82,69,65,68,32,73,
 84,46,0,72,65,78,68,83,32,79,70,70,32,84,72,69,32,67,65,82,84,82,73,68,
 71,69,46,0,87,72,65,84,32,89,69,65,82,63,32,65,76,87,65,89,83,32,84,72,
 69,32,76,65,83,84,32,79,78,69,46,0,73,84,32,73,83,32,78,79,84,32,65,32,
 82,73,68,68,76,69,46,32,73,84,32,73,83,32,49,57,57,57,46,0,84,72,69,32,
 77,79,79,78,32,87,79,82,75,83,32,78,79,87,46,32,84,72,65,78,75,32,89,79,
 85,46,0,84,72,65,84,32,73,83,32,78,79,84,32,72,79,87,32,67,65,82,84,82,
 73,68,71,69,83,32,87,79,82,75,46,0,89,79,85,32,83,65,73,68,32,89,79,85,
 32,87,79,85,76,68,32,67,79,77,69,32,66,65,67,75,46,1,32,68,73,68,32,89,
 79,85,32,66,82,73,78,71,32,18,63,0,76,65,83,84,32,84,73,77,69,32,89,79,
 85,32,83,65,73,68,32,76,65,84,69,82,46,32,73,84,32,73,83,32,76,65,84,69,
 82,32,78,79,87,44,32,21,46,0,89,79,85,32,71,65,86,69,32,79,78,69,32,79,
 70,32,85,83,32,83,79,77,69,84,72,73,78,71,46,32,84,72,69,32,20,32,83,84,
 73,76,76,32,84,65,76,75,83,32,65,66,79,85,84,32,73,84,46,0,79,85,82,32,
 83,72,69,76,70,32,72,65,83,32,89,79,85,82,32,70,73,78,71,69,82,80,82,73,
 78,84,83,32,79,78,32,73,84,46,0,83,84,73,76,76,32,67,65,82,82,89,73,78,
 71,32,17,63,32,89,79,85,32,78,69,86,69,82,32,76,69,84,32,71,79,46,0,89,
 79,85,32,83,72,79,87,69,68,32,85,83,32,79,78,69,32,66,69,70,79,82,69,46,
 32,84,72,69,78,32,89,79,85,32,75,69,80,84,32,73,84,46,0,84,72,69,32,76,
 65,83,84,32,79,70,32,85,83,32,89,79,85,32,77,69,84,32,87,69,78,84,32,72,
 79,77,69,32,69,77,80,84,89,46,0,89,79,85,32,83,65,73,68,32,78,79,32,76,
 65,83,84,32,84,73,77,69,46,32,73,84,32,67,65,77,69,32,84,72,82,79,85,71,
 72,32,84,72,69,32,87,65,76,76,46,0,89,79,85,32,65,83,75,69,68,32,83,79,
 32,77,65,78,89,32,81,85,69,83,84,73,79,78,83,32,76,65,83,84,32,84,73,77,
 69,46,1,32,65,83,75,32,79,78,69,32,77,79,82,69,46,0,89,79,85,32,68,82,
 73,86,69,32,65,32,72,65,82,68,32,68,69,65,76,46,32,87,69,32,67,79,85,78,
 84,69,68,32,84,72,69,32,84,82,85,84,72,83,32,87,69,32,79,87,69,46,0,84,
 72,69,32,18,32,89,79,85,32,71,65,86,69,32,85,83,32,87,65,83,32,83,79,32,
 76,73,71,72,84,46,1,32,87,69,32,72,65,86,69,32,78,79,84,32,79,80,69,78,
 69,68,32,73,84,46,0,84,72,69,32,76,65,83,84,32,18,32,89,79,85,32,72,65,
 78,68,69,68,32,85,83,32,87,65,83,32,69,77,80,84,89,46,0,87,69,32,79,80,
 69,78,69,68,32,89,79,85,82,32,71,73,70,84,46,1,32,78,79,84,72,73,78,71,
 46,32,83,79,44,32,21,46,46,46,0,84,72,69,32,20,32,83,84,73,76,76,32,83,
 72,65,75,69,83,32,70,82,79,77,32,76,65,83,84,32,84,73,77,69,46,0,75,69,
 69,80,32,89,79,85,82,32,86,79,73,67,69,32,68,79,87,78,32,84,79,68,65,89,
 46,32,80,76,69,65,83,69,46,0,87,69,32,72,73,68,32,79,85,82,32,84,72,73,
 78,71,83,32,87,72,69,78,32,87,69,32,83,65,87,32,89,79,85,32,67,79,77,73,
 78,71,46,0,84,72,69,89,32,83,84,73,76,76,32,82,69,80,69,65,84,32,87,72,
 65,84,32,89,79,85,32,83,65,73,68,32,65,66,79,85,84,32,85,83,46,0,76,65,
 85,71,72,32,65,71,65,73,78,44,32,21,46,32,87,69,32,75,69,80,84,32,65,32,
 82,69,67,79,82,68,73,78,71,46,0,89,79,85,82,32,76,73,71,72,84,32,73,83,
 32,83,84,73,76,76,32,79,78,32,79,85,82,32,87,65,76,76,83,46,0,83,73,78,
 67,69,32,89,79,85,32,67,65,77,69,44,32,84,72,69,32,20,32,72,85,77,83,32,
 83,79,70,84,69,82,46,0,83,79,77,69,79,78,69,32,82,69,65,68,32,79,85,82,
 32,67,65,67,72,69,46,32,73,84,32,70,69,76,84,32,76,73,75,69,32,89,79,85,
 46,0,79,85,82,32,77,69,77,79,82,73,69,83,32,65,82,69,32,77,73,83,83,73,
 78,71,32,65,32,80,65,71,69,44,32,21,46,0,72,69,76,76,79,44,32,21,46,1,
 32,72,69,76,76,79,32,73,83,32,65,32,72,65,76,76,87,65,89,46,32,83,79,77,
 69,79,78,69,32,84,79,76,68,32,77,69,46,0,73,32,72,65,86,69,32,66,69,69,
 78,32,83,65,89,73,78,71,32,17,32,66,65,67,75,87,65,82,68,83,32,65,76,76,
 32,68,65,89,46,0,73,32,67,72,69,67,75,69,68,32,77,89,32,80,79,67,75,69,
 84,32,70,79,82,32,65,32,83,85,78,32,84,79,68,65,89,46,1,32,87,72,89,63,
 0,83,79,77,69,79,78,69,32,76,69,70,84,32,65,32,82,73,68,68,76,69,32,73,
 78,32,84,72,69,32,20,46,32,73,83,32,84,72,69,32,65,78,83,87,69,82,32,17,
 63,0,84,72,69,32,67,65,82,80,69,84,32,83,65,89,83,32,89,79,85,32,87,69,
 82,69,32,72,69,82,69,46,32,73,84,32,83,65,89,83,32,73,84,32,73,78,32,67,
 79,76,79,85,82,83,46,0,3,21,46,32,3,21,46,32,84,72,69,32,76,73,71,72,
 84,83,32,76,69,65,82,78,69,68,32,65,32,78,65,77,69,46,0,
};
#endif
#endif
