/* Generated by the asset toolchain (not part of this repository); do not edit. */
#define TEXT_LINES 916u
uint8_t crucible_line_raw(uint16_t id,uint8_t*out,uint8_t n) BANKED;
uint8_t crucible_dict_word(uint16_t w,char*out,uint8_t n) BANKED;
uint8_t crucible_line_meta(uint16_t id) BANKED;
