#ifndef CRUCIBLE_ROOM_DATA_H
#define CRUCIBLE_ROOM_DATA_H
/* Generated by the art toolchain (not part of this repository); do not edit. The living rooms' vocabulary. */
#include <stdint.h>
#define ROOM_FAMILIES 12u
#define ROOM_SKIES 7u
#define ROOM_FLOORS 6u
#define ROOM_DRIFTS 6u
#define ROOM_CRITTERS 6u
#define ROOM_WHISPERS 12u
#define ROOM_MAX_TILES 95u
#define ROOM_BLANK 116u
/* sprite tiles: drifters replace the cloud tiles; critters (two frames each), then door x2 and glitch x2 */
#define ROOM_SPR_DRIFT 77u
#define ROOM_SPR_CRITTER 112u
#define ROOM_SPR_DOOR 124u
#define ROOM_SPR_GLITCH 126u
/* a family's colours (roomgfx_colours), in this order */
#define ROOM_C_SKY 0u
#define ROOM_C_PLASTER 4u
#define ROOM_C_FLOOR 5u
#define ROOM_C_MUTED 9u
#define ROOM_C_DRIFT 13u
#define ROOM_C_DIM_SKY 16u
#define ROOM_C_DIM_FLOOR1 20u
#define ROOM_C_CYCLE 21u
#define ROOM_C_GLITCH_SKY 30u
#define ROOM_C_HOSTILE 34u
#define ROOM_C_HOSTILE_PLASTER 38u
#define ROOM_C_SIZE 39u
#define ROOM_FLASH_WHITE 32767u
#define ROOM_FLASH_BLUE 32004u
/* named picks the composer's secrets use */
#define ROOM_SKY_OBSERVATORY 1u
#define ROOM_FLOOR_TRON 1u
#define ROOM_DRIFT_STATIC 3u
#define ROOM_DRIFT_GLYPHS 4u
#define ROOM_CRITTER_GHOST 3u
#define ROOM_CRITTER_CURSOR 4u
#define ROOM_FAMILY_VOID 9u
#define ROOM_FAMILY_TRON 10u
#define ROOM_SKY_FRAMED 62u
#ifdef ROOM_TABLES
/* tiers: 0 pastel, 1 soft, 2 strange */
static const uint8_t room_tier0[]={0,1,2,3};
static const uint8_t room_tier1[]={4,5,6};
static const uint8_t room_tier2[]={7,8,9,10,11};
#define ROOM_TIER_N0 4u
#define ROOM_TIER_N1 3u
#define ROOM_TIER_N2 5u
/* per family: which skies, floors, drifters and critters it may use (bit masks) */
static const uint8_t room_fam_sky[]={83,73,85,99,50,22,42,12,42,38,58,14};
static const uint8_t room_fam_floor[]={51,13,37,27,26,42,26,20,50,26,34,13};
static const uint8_t room_fam_drift[]={35,7,7,35,35,19,44,28,56,56,56,14};
static const uint8_t room_fam_critter[]={19,35,41,22,26,35,42,21,52,26,28,11};
static const uint8_t room_lean_family[]={7,8,9,10,6,4,11,5};
#endif
/* banked accessors (crucible_room_gfx.c, crucible_room_gfx2.c) */
#ifndef ROOM_PURE
#include <gb/gb.h>
uint8_t roomgfx_common(uint8_t base) BANKED;                    /* uploads the common tiles; returns their count */
void roomgfx_hud_row(uint8_t r,uint8_t*map,uint8_t*attr) BANKED; /* r 0: row 0; 1..3: rows 15..17 */
void roomgfx_card_row(uint8_t r,uint8_t*map,uint8_t*attr) BANKED;/* rows 9..14, columns 1..18 */
uint8_t roomgfx_sky_count(uint8_t k) BANKED;
void roomgfx_sky_upload(uint8_t k,uint8_t first,uint8_t n,uint8_t base) BANKED;
void roomgfx_sky_row(uint8_t k,uint8_t r,uint8_t*map,uint8_t*attr) BANKED;   /* r 0..6: rows 1..7 */
void roomgfx_sky_tile(uint8_t k,uint8_t i,uint8_t*out) BANKED;
uint8_t roomgfx_twinkle(uint8_t k,uint8_t n) BANKED;             /* a sparkle tile of sky k (255: none) */
void roomgfx_critters(void) BANKED;
uint8_t roomgfx_floor_count(uint8_t k) BANKED;
void roomgfx_floor_upload(uint8_t k,uint8_t first,uint8_t n,uint8_t base) BANKED;
void roomgfx_floor_row(uint8_t k,uint8_t r,uint8_t*map,uint8_t*attr) BANKED; /* r 0..6: rows 8..14 */
void roomgfx_floor_tile(uint8_t k,uint8_t i,uint8_t*out) BANKED;
void roomgfx_drift(uint8_t k) BANKED;
void roomgfx_colours(uint8_t f,uint8_t first,uint8_t n,uint16_t*out) BANKED;
uint8_t roomgfx_whisper(uint8_t k,char*out) BANKED;              /* returns its length */
#endif
#endif
