/* Generated by the table toolchain (not part of this repository); do not edit. The world catalogue as one blob of 271248 bytes in 17
 * banked chunks (crucible_cat_<k>.c; manifest crucible_cat.json). Chunk k holds blob bytes [k<<14, (k+1)<<14) at 0x4000 of
 * its bank: off = offset[TAB] + i*elem, bank = bank[off >> 14], address = 0x4000 | (off & 0x3FFF). */
#ifndef CRUCIBLE_CAT_H
#define CRUCIBLE_CAT_H
#include <stdint.h>
#define CRUCIBLE_CAT_ITEMS 5629u
#define CRUCIBLE_CAT_RECIPES 13439u
#define CRUCIBLE_CAT_CATEGORIES 7u
#define CRUCIBLE_CAT_CHUNKS 17u
#define CRUCIBLE_CAT_CHUNK_SHIFT 14
#define CRUCIBLE_CAT_BLOB_BYTES 271248ul
/* blob offset of each table, by TAB_* (crucible_core.h) */
#define CRUCIBLE_CAT_OFF_CATEGORY 0x00002ul
#define CRUCIBLE_CAT_OFF_TRAITS 0x01600ul
#define CRUCIBLE_CAT_OFF_STARTERS 0x041faul
#define CRUCIBLE_CAT_OFF_SHELF 0x044baul
#define CRUCIBLE_CAT_OFF_SHELF_POS 0x070b4ul
#define CRUCIBLE_CAT_OFF_RECIPE_A 0x09caeul
#define CRUCIBLE_CAT_OFF_RECIPE_B 0x105acul
#define CRUCIBLE_CAT_OFF_RECIPE_R 0x16eaaul
#define CRUCIBLE_CAT_OFF_RECIPE_BIT 0x1d7a8ul
#define CRUCIBLE_CAT_OFF_RECIPE_SWAP 0x240a6ul
#define CRUCIBLE_CAT_OFF_DEPTH 0x24736ul
#define CRUCIBLE_CAT_OFF_ROUTE_FIRST 0x25d34ul
#define CRUCIBLE_CAT_OFF_ROUTE_LIST 0x28930ul
#define CRUCIBLE_CAT_OFF_TRAIT_SHELF 0x2f22eul
#define CRUCIBLE_CAT_OFF_TRAIT_RANK 0x3132eul
#define CRUCIBLE_CAT_OFFSETS {CRUCIBLE_CAT_OFF_CATEGORY,CRUCIBLE_CAT_OFF_TRAITS,CRUCIBLE_CAT_OFF_STARTERS,CRUCIBLE_CAT_OFF_SHELF,CRUCIBLE_CAT_OFF_SHELF_POS,CRUCIBLE_CAT_OFF_RECIPE_A,CRUCIBLE_CAT_OFF_RECIPE_B,CRUCIBLE_CAT_OFF_RECIPE_R,CRUCIBLE_CAT_OFF_RECIPE_BIT,CRUCIBLE_CAT_OFF_RECIPE_SWAP,CRUCIBLE_CAT_OFF_DEPTH,CRUCIBLE_CAT_OFF_ROUTE_FIRST,CRUCIBLE_CAT_OFF_ROUTE_LIST,CRUCIBLE_CAT_OFF_TRAIT_SHELF,CRUCIBLE_CAT_OFF_TRAIT_RANK}
/* for the cartridge's own screens (the core never reads these) */
#define CRUCIBLE_CAT_OFF_NAMES 0x31b6eul /* 12 bytes per id: native name, NUL-padded */
#define CRUCIBLE_CAT_NAME_BYTES 12u
#define CRUCIBLE_CAT_OFF_CATEGORY_NAMES 0x4234aul /* 10 bytes each */
#define CRUCIBLE_CAT_CATEGORY_NAME_BYTES 10u
/* the chunks and their banks. A bank can pass 255 on an 8 MB cartridge: take the full value at run time,
 * (uint16_t)&__bank_crucible_cat_<k> (GBDK's BANK() keeps only 8 bits; SDCC accepts the 16-bit form in code, not in a
 * static initialiser). CRUCIBLE_CAT_BANKS(out) fills uint16_t out[CRUCIBLE_CAT_CHUNKS]. */
#ifdef __SDCC
#include <gb/gb.h>
BANKREF_EXTERN(crucible_cat_0)
BANKREF_EXTERN(crucible_cat_1)
BANKREF_EXTERN(crucible_cat_2)
BANKREF_EXTERN(crucible_cat_3)
BANKREF_EXTERN(crucible_cat_4)
BANKREF_EXTERN(crucible_cat_5)
BANKREF_EXTERN(crucible_cat_6)
BANKREF_EXTERN(crucible_cat_7)
BANKREF_EXTERN(crucible_cat_8)
BANKREF_EXTERN(crucible_cat_9)
BANKREF_EXTERN(crucible_cat_10)
BANKREF_EXTERN(crucible_cat_11)
BANKREF_EXTERN(crucible_cat_12)
BANKREF_EXTERN(crucible_cat_13)
BANKREF_EXTERN(crucible_cat_14)
BANKREF_EXTERN(crucible_cat_15)
BANKREF_EXTERN(crucible_cat_16)
#define CRUCIBLE_CAT_BANKS(out) do { \
  (out)[0] = (uint16_t)&__bank_crucible_cat_0; \
  (out)[1] = (uint16_t)&__bank_crucible_cat_1; \
  (out)[2] = (uint16_t)&__bank_crucible_cat_2; \
  (out)[3] = (uint16_t)&__bank_crucible_cat_3; \
  (out)[4] = (uint16_t)&__bank_crucible_cat_4; \
  (out)[5] = (uint16_t)&__bank_crucible_cat_5; \
  (out)[6] = (uint16_t)&__bank_crucible_cat_6; \
  (out)[7] = (uint16_t)&__bank_crucible_cat_7; \
  (out)[8] = (uint16_t)&__bank_crucible_cat_8; \
  (out)[9] = (uint16_t)&__bank_crucible_cat_9; \
  (out)[10] = (uint16_t)&__bank_crucible_cat_10; \
  (out)[11] = (uint16_t)&__bank_crucible_cat_11; \
  (out)[12] = (uint16_t)&__bank_crucible_cat_12; \
  (out)[13] = (uint16_t)&__bank_crucible_cat_13; \
  (out)[14] = (uint16_t)&__bank_crucible_cat_14; \
  (out)[15] = (uint16_t)&__bank_crucible_cat_15; \
  (out)[16] = (uint16_t)&__bank_crucible_cat_16; \
} while (0)
#endif
/* a crucible_tables for far reads: every array pointer NULL, the baked facts (CRUCIBLE_CAT_TABLES(&cru_rules_world)) */
#define CRUCIBLE_CAT_TABLES(rules) {CRUCIBLE_CAT_ITEMS,CRUCIBLE_CAT_RECIPES,CRUCIBLE_CAT_CATEGORIES,\
 0,0,0,0,0,0,0,0,0,0,0,0,0,(rules),0,0,\
 181,{0,226,518,830,1093,2713,5044,5629},{5629,226,292,312,263,1620,2331,585,376,296,648,782,435,2435,1461,1721,1017,2610,773,574}}
#endif
