#ifndef CRUCIBLE_UI_H
#define CRUCIBLE_UI_H
#include <gb/gb.h>
/* Generated by the art toolchain (not part of this repository); do not edit. Background UI tiles start at 96; sprite UI tiles start at 64. */
#define UI_RULE 96u
#define UI_BOOK 97u
#define UI_STAR 98u
#define UI_PLUS 99u
#define UI_EQUALS 100u
#define UI_LEFT 101u
#define UI_RIGHT 102u
#define UI_A 103u
#define UI_B 104u
#define UI_CURSOR 105u
#define UI_HOURGLASS 106u
#define UI_LINK 107u
#define UI_RINGC 108u
#define UI_RINGH 109u
#define UI_RINGV 110u
#define UI_PIP_ON 111u
#define UI_PIP_OFF 112u
#define UI_TOAST_CORNER 113u
#define UI_TOAST_EDGE 114u
#define UI_TOAST_SIDE 115u
#define UI_BLANK 116u
#define UI_QUESTION 117u
#define UI_CROSS 121u
#define SPR_ARROW0 64u
#define SPR_ARROW1 65u
#define SPR_ARROW_R 66u
#define SPR_SPARK0 67u
#define SPR_SPARK1 68u
#define SPR_SPARK2 69u
#define SPR_BUBBLE0 70u
#define SPR_BUBBLE1 71u
#define SPR_MOTE 72u
#define SPR_BOX 73u
#define SPR_CLOUD0 74u
#define SPR_CLOUD1 75u
#define SPR_CLOUD2 76u
#define SPR_CLOUD_S0 77u
#define SPR_CLOUD_S1 78u
#define SPR_CLOUD_M0 79u
#define SPR_CLOUD_M1 80u
#define SPR_CLOUD_M2 81u
#define SPR_CLOUD_M3 82u
#define SPR_CLOUD_M4 83u
#define SPR_CLOUD_M5 84u
#define SPR_CLOUD_L0 85u
#define SPR_CLOUD_L1 86u
#define SPR_CLOUD_L2 87u
#define SPR_CLOUD_L3 88u
#define SPR_CLOUD_L4 89u
#define SPR_CLOUD_L5 90u
#define SPR_CLOUD_L6 91u
#define SPR_CLOUD_L7 92u
#define UI_FONT 128u
/* glyph tile of a character: lower case shares the upper-case glyphs */
#define GLYPH(c) ((uint8_t)((c)>=32u&&(c)<96u?UI_FONT+(c)-32u:(c)>=96u&&(c)<128u?UI_FONT+(c)-64u:UI_FONT))
#define BURST_FRAMES 40u
#define BURST_PARTS 12u
void crucible_load_ui(void) BANKED;
/* ui, shade and accent palettes (12 colours): banked constants must be copied out through this call. */
void crucible_ui_palettes(uint16_t*) BANKED;
void crucible_burst_xy(uint8_t,uint8_t,uint8_t*) BANKED;
#endif
