#ifndef CRUCIBLE_SCENE_H
#define CRUCIBLE_SCENE_H
#include <gb/gb.h>
/* Generated by the art toolchain (not part of this repository); do not edit. Text attributes: font colour 3 (violet ink on pages and the white HUD). */
enum { SCENE_BENCH, SCENE_REVEAL, SCENE_BOOK, SCENE_RECORDS, SCENE_MENU };
#define PAL_PLASTER 0u
#define PAL_SKY 2u
#define PAL_MUTED 4u
#define PAL_WOOD 7u
void scene_draw(uint8_t) BANKED;
void scene_begin(uint8_t) BANKED; /* scene_draw in parts: the tiles, then scene_rows(n) a few rows at a time */
uint8_t scene_rows(uint8_t n) BANKED;
void scene_twinkle(uint8_t) BANKED;
/* plaster, sky, wood, muted (16 colours) */
void scene_palettes(uint16_t *) BANKED;
uint16_t crucible_plaster(uint8_t) BANKED;
/* menu chrome, marble and katakana palettes (12 colours, for BG palettes 1, 3 and 5) */
void scene_menu_palettes(uint16_t *) BANKED;
void scene_cell(uint8_t id, uint8_t x, uint8_t y, uint8_t *tile, uint8_t *attr) BANKED;
/* Title sky clouds: chunk k's box in the menu map {column,row,width,height}, stashed offscreen. */
#define SCENE_CLOUD_CHUNKS 6u
void scene_cloud_chunk(uint8_t k, uint8_t *box) BANKED;
#endif
